function GUI_makeGUI_MiddlePanel(hTabGroup)
% draws the secondary axes window on the right

[color] =  GUI_Colors();

%% BELOW IMAGE
xleft1 = 0.01;
xleft2 = 0.15;
xleft3 = xleft2+0.1;

yheight1 = 0.03;

ypos1 = 0.33;
ypos2 = ypos1 + 0.03;
ypos3 = ypos2 + 0.025;

txtPosition = uicontrol(hTabGroup,'Style','text',...
                'Tag','txtPosition',...
                'String','X: ??? Y: ???','Units','normalized',...
                'BackgroundColor',color.bgc{2},...
                'HorizontalAlignment','Left',...
                'FontSize',8,...
                'Position',[xleft1 ypos3 0.3 yheight1]);
txtValue = uicontrol(hTabGroup,'Style','text',...
                'Tag','txtValue',...
                'String','Value: ???','Units','normalized',...
                'BackgroundColor',color.bgc{2},...
                'HorizontalAlignment','Left',...
                'FontSize',8,...
                'Position',[0.85 ypos3 0.5 yheight1]);
            
txtCurrentSelect = uicontrol(hTabGroup,'Style','text',...
                'Tag','txtCurrentSelect',...
                'String','Current Data Selection','Units','normalized',...
                'HorizontalAlignment','Center',...
                'BackgroundColor',color.bgc{2},...
                'FontSize',8,...
                'Position',[xleft2 ypos3 0.7 yheight1]);            
            
sldSelectedFile = uicontrol(hTabGroup,'Style','slider',...
                'Tag','sldSelectedFile',...
                'Min',1,'Max',2,'Value',1,...
                'Callback',@GUI_Callback_sldSelectedFile,...
                'Units','normalized',...
                'HorizontalAlignment','Left',...                
                'Position',[xleft2 ypos2 0.7 yheight1]);

editSelectedFile = uicontrol(hTabGroup,'Style','edit',...
                'Tag','editSelectedFile',...
                'Callback',@GUI_Callback_editSelectedFile,...
                'BackgroundColor',color.bgc{1},...
                'String','##','Units','normalized',...
                'HorizontalAlignment','Left',...
                'FontSize',10,...
                'Position',[xleft3 ypos1 0.05 yheight1]);      
            
txtTotalFile = uicontrol(hTabGroup,'Style','text',...
                'Tag','txtTotalFile',...
                'String','/###:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'BackgroundColor',color.bgc{2},...
                'FontSize',10,...
                'Position',[xleft3+0.05 ypos1 0.06 yheight1]);  
            
txtCurrentFile = uicontrol(hTabGroup,'Style','text',...
                'Tag','txtCurrentFile',...
                'String','Fakey McFakeDataSet132048','Units','normalized',...
                'HorizontalAlignment','Left',...
                'BackgroundColor',color.bgc{2},...
                'FontSize',10,...
                'Position',[xleft3+0.11 ypos1 0.7 yheight1]);  

%% Below images

% axesSupport = axes('Position',[0.2 0.35 0.75 0.5],'Parent',hTabGroup,...
%                     'Tag','axesSupport');
% 
% heightval = 0.03;
% width1 = 0.14;
% width2 = 0.06;
% width3 = 0.35;
% width4 = 0.2;
% left1 = 0.05;
% left2 = left1+width1+0.02;
% left3 = left2+width2+0.02;
% left4 = left3+width3+0.02;
% height1 = 0.0;
% height2 = height1+heightval;
% height3 = height2+heightval;
% 
% sldMinLimits = uicontrol(hTabGroup,'Style','slider',...
%                 'Tag','sldMinLimits',...
%                 'Callback',@GUI_Callback_btnLimitMinMax,...
%                 'Units','normalized',...
%                 'HorizontalAlignment','Left',...
%                 'Position',[left3 height2 width3 yheight1]);
% sldMaxLimits = uicontrol(hTabGroup,'Style','slider',...
%                 'Tag','sldMaxLimits',...
%                 'Callback',@GUI_Callback_btnLimitMinMax,...
%                 'Units','normalized',...
%                 'HorizontalAlignment','Left',...
%                 'Position',[left3 height1 width3 yheight1]);            
% chkAutoLimits = uicontrol(hTabGroup,'Tag','chkAutoLimits',...
%                 'Style','checkbox','Value',1,...
%                 'BackgroundColor',color.bgc{2},...
%                 'Callback',@GUI_Callback_autoCheck,...
%                 'String','Auto Limits','Units','normalized',...
%                 'HorizontalAlignment','Right',...
%                 'Position',[left4-0.05 height3 0.3 yheight1]);        
% 
% txtMinValue = uicontrol(hTabGroup,'Style','edit',...
%                 'Tag','txtMinValue',...
%                 'Callback',@GUI_Callback_txtLimitMinMax,...
%                 'String','0','Units','normalized',...
%                 'HorizontalAlignment','Center',...
%                 'BackgroundColor',color.bgc{1},...
%                 'FontSize',10,...
%                 'Position',[left4 height2 width4/2 yheight1]);  
% txtMaxValue = uicontrol(hTabGroup,'Style','edit',...
%                 'Tag','txtMaxValue',...
%                 'Callback',@GUI_Callback_txtLimitMinMax,...
%                 'String','1','Units','normalized',...
%                 'BackgroundColor',color.bgc{1},...
%                 'HorizontalAlignment','Center',...
%                 'FontSize',10,...
%                 'Position',[left4 height1 width4/2 yheight1]);              

% btnContrastTighter = uicontrol(hTabGroup,'Style','pushbutton',...
%                 'Tag','btnContrastTighter',...
%                 'Callback',@GUI_Callback_btnContrastTighter,...
%                 'String','In','Units','normalized',...
%                 'HorizontalAlignment','Left',...
%                 'FontSize',10,...
%                 'Position',[left1 height2 width1 yheight1]);  
% btnContrastLooser = uicontrol(hTabGroup,'Style','pushbutton',...
%                 'Tag','btnContrastLooser',...
%                 'Callback',@GUI_Callback_btnContrastLooser,...
%                 'String','Out','Units','normalized',...
%                 'HorizontalAlignment','Left',...
%                 'FontSize',10,...
%                 'Position',[left1 height1 width1 yheight1]); 
            
% txtDataType = uicontrol(hTabGroup,'Style','text',...
%                 'Tag','txtDatatype',...
%                 'String','Image Contrast Limits','Units','normalized',...
%                 'HorizontalAlignment','Left',...
%                 'BackgroundColor',color.bgc{2},...
%                 'FontSize',10,...
%                 'Position',[left2 height3 2*width4 yheight1]);  
% txtMinLimits = uicontrol(hTabGroup,'Style','text',...
%                 'Tag','txtMinLimits',...
%                 'String','Min:','Units','normalized',...
%                 'HorizontalAlignment','Left',...
%                 'BackgroundColor',color.bgc{2},...
%                 'FontSize',10,...
%                 'Position',[left2 height2 width2 yheight1]);  
% txtMaxLimits = uicontrol(hTabGroup,'Style','text',...
%                 'Tag','txtMaxLimits',...
%                 'String','Max:','Units','normalized',...
%                 'HorizontalAlignment','Left',...
%                 'BackgroundColor',color.bgc{2},...
%                 'FontSize',10,...
%                 'Position',[left2 height1 width2 yheight1]);
                      