function GUI_makeGUI_DataSetPanel(hTabGroup)
% draws the log axes window on the right
[color] =  GUI_Colors();

panelScan = uipanel(hTabGroup,...
        'Position',[0.55 0.0 0.3 1],...
        'Title','Current Scan',...
        'BackgroundColor',color.bgc{1});
txtScanPos = uicontrol('Parent',panelScan,...
    'Style','text',...
    'Tag','txtScanPos',...
    'String','100/100','Units','normalized',...
    'BackgroundColor',color.bgc{1},...
    'HorizontalAlignment','Center',...
    'FontSize',10,...
    'Position',[0 0 1 1]);