function GUI_makeGUI_BrowseAndTxtBox(hTabGroup,strName,strLongName,strName2,height1,handlesBox,handlesText)
heightval = 0.03;
heightbtn = heightval+0.01;
width1 = 0.6;
width2 = 0.25;
left1 = 0.05;
left2 = left1+width1+0.02;
height2 = height1+heightval;
fontSize1 = 9;

[color] =  GUI_Colors();


txtDataType = uicontrol(hTabGroup,'Style','text',...
                'Tag',['txtDatatype_' strName],...
                'String',strLongName,'Units','normalized',...
                'HorizontalAlignment','Left',...
                'BackgroundColor',color.bgc{2},...
                'FontSize',fontSize1,...
                'Position',[left1 height2 width1 heightval]);

txtValue = uicontrol(hTabGroup,'Style','edit',...
                'Tag',['txtValue' strName],...
                'Callback',handlesText,...
                'BackgroundColor',color.bgc{1},...
                'String',strName2,'Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[left1 height1 width1 heightval]);

btnBrowse = uicontrol(hTabGroup,'Style','pushbutton',...
                'Tag',['btnBrowse' strName],...
                'Callback',handlesBox,...
                'String','Browse',...
                'Units','normalized',...
                'FontSize',fontSize1,...
                'HorizontalAlignment','Left',...
                'Position',[left2 height1 width2 heightbtn]);