function GUI_makeGUI_SliderAndChkBox(hTabGroup,strName,strLong,strUnits,height1,minV,maxV,val,handlesSld,handlesText,handlesChkEnabled)
heightval = 0.07;
heightvaltext = 0.08;
heightoffsettext = 0.00;
width1 = 0.02;
width2 = 0.25;
width3 = 0.40;
width4 = 0.2;
left1 = 0.01;
left2 = left1+width1+0.02;
left3 = left2+width2+0.02;
left4 = left3+width3+0.02;
height2 = height1+heightval;
height3 = height2+heightval;
fontSize1 = 10;
fontSize2 = 12;
fontSize3 = 8;

[color] =  GUI_Colors();

txtDataType = uicontrol(hTabGroup,'Style','text',...
                'Tag',['txtDatatype_' strName],...
                'String',strLong,'Units','normalized',...
                'HorizontalAlignment','Left',...
                'BackgroundColor',color.bgc{2},...
                'FontSize',fontSize1,...
                'Position',[left2 height3 width2+width3 heightval]);  
            
sldLimits = uicontrol(hTabGroup,'Style','slider',...
                'Tag',['sldLimits' strName],...
                'Min',minV,...
                'Max',maxV,...
                'Value',val,...
                'Callback',handlesSld,...
                'BackgroundColor',color.bgc{2},...
                'Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[left3 height2 width3 heightval]);              

txtValue = uicontrol(hTabGroup,'Style','edit',...
                'Tag',['txtValue' strName],...
                'Callback',handlesText,...
                'BackgroundColor',color.bgc{2},...
                'Enable','on',...
                'String',num2str(val),...
                'Units','normalized',...
                'HorizontalAlignment','Left',...
                'FontSize',fontSize1,...
                'Position',[left4 height2+heightoffsettext width4 heightvaltext]);                
chkEnabled= uicontrol(hTabGroup,'Tag',['chkEnabled' strName],...
                'Style','checkbox','Value',1,...
                'Callback',handlesChkEnabled,...
                'BackgroundColor',color.bgc{2},...
                'String','Enable','Units','normalized',...
                'HorizontalAlignment','Right',...
                'FontSize',fontSize1,...
                'Position',[left4 height3 width3 heightval]);  
            
txtLimits = uicontrol(hTabGroup,'Style','text',...
                'Tag',['txtLimits' strName],...
                'String',strUnits,'Units','normalized',...
                'HorizontalAlignment','Left',...
                'BackgroundColor',color.bgc{2},...
                'FontSize',fontSize3,...
                'Position',[left2 height2 width2 heightval]);  