function GUI_makeGUI_LeftPanel(hTabGroup,M_version)
% draws the main parameter panel on the left
if strcmpi(M_version,'2009a')
    tabWelcome = uitab('v0',hTabGroup, 'title','Welcome');
    tabChipInfo = uitab('v0',hTabGroup, 'title','Chip Info');
    tabHardwareCtrl = uitab('v0',hTabGroup, 'title','Instrument');
    tabAcquisition = uitab('v0',hTabGroup,'title','Acquisition');
    tabProcess = uitab('v0',hTabGroup, 'title','Processing');
    tabOptions = uitab('v0',hTabGroup, 'title','Options');
    set(hTabGroup,'SelectedIndex',1); %start in welcome screen
else
    tabWelcome = uitab(hTabGroup, 'title','Welcome');
    tabChipInfo = uitab(hTabGroup, 'title','Chip Info');
    tabHardwareCtrl = uitab(hTabGroup, 'title','Instrument');
    tabAcquisition = uitab(hTabGroup,'title','Acquisition');
    tabProcess = uitab(hTabGroup, 'title','Processing');
    tabOptions = uitab(hTabGroup, 'title','Options');
    set(hTabGroup,'SelectedTab',tabWelcome); %start in welcome screen
end
[color] =  GUI_Colors();

%% Format variables
leftX = 0.05;
panelLeftX = leftX - 0.02;

rightX = 0.25;
rightXwidth = 0.67;

rightX2 = 0.4;
txtOffset = 0.01;

thirdX1 = 0.01;
thirdX2 = 0.35;
thirdX3 = thirdX2+0.3;

thirdwidth = 0.28;
thirdwidth2 = 0.2;
thirdX2width = 0.59;

centerX = 0.5;
centerbtn = 0.2;

height1 = 0.06;
height2 = 0.08;
height3 = 0.03;
reset = 0.95;

width = 0.3;
widthleft = 0.35;
widthright = 0.5;
widthbtn = 0.9;
widthbtn2 = 0.6;
widthtotal = 0.9;
panelWidth = widthtotal+0.04;

%% TAB Welcome
currentheight = reset;

txtWelcomeText = uicontrol(tabWelcome,'Style','text',...
                'Tag','txtWelcomeText',...
                'BackgroundColor',color.bgc{2},...
                'String','Welcome to SP-IRIS Acquisition','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight widthtotal height3]);
currentheight = currentheight - height1;

% txtWhatToDoText = uicontrol(tabWelcome,'Style','text',...
%                 'Tag','txtWhatToDoText',...
%                 'BackgroundColor',color.bgc{2},...
%                 'String','Follow the steps below.','Units','normalized',...
%                 'HorizontalAlignment','Left',...
%                 'Position',[leftX currentheight widthtotal height1]);
% currentheight = currentheight - height2;

btnWelcomeChipInfo = uicontrol(tabWelcome,'Tag','btnWelcomeChipInfo',...
                'Style','pushbutton',...
                'String','1) Enter Array Information','Units','normalized',...
                'Callback',@GUI_Callback_btnWelcome_ChipInfo,...
                'HorizontalAlignment','Left',...
                'Position',[centerbtn currentheight widthbtn2 height1]);
currentheight = currentheight - height2;

btnWelcomeLoadChip = uicontrol(tabWelcome,'Tag','btnWelcomeLoadChip',...
                'Style','pushbutton',...
                'String','2) Load the sensor chip','Units','normalized',...
                'Callback',@GUI_Callback_btnWelcome_LoadChip,...
                'HorizontalAlignment','Left',...
                'Position',[centerbtn currentheight widthbtn2 height1]);
currentheight = currentheight - height2;

btnWelcomeFocus = uicontrol(tabWelcome,'Tag','btnWelcomeFocus',...
                'Style','pushbutton',...
                'String','3) Focus','Units','normalized',...
                'Callback',@GUI_Callback_btnWelcome_Focus,...
                'HorizontalAlignment','Left',...
                'Position',[centerbtn currentheight widthbtn2 height1]);
% currentheight = currentheight - height2;
% 
% btnWelcomeMinimap = uicontrol(tabWelcome,'Tag','btnWelcomeMinimap','Style','pushbutton',...
%                 'String','4) Minimap (Optional)','Units','normalized',...
%                 'Callback',@GUI_Callback_btnWelcome_Minimap,...
%                 'Position',[centerbtn currentheight widthbtn2 height1]);
currentheight = currentheight - 2.2*height2;

panelManAcquire = uipanel(tabWelcome,...
                'Tag','panelManAcquire',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BorderType','line',...
                'BackgroundColor',color.bgc{2},...
                'Title','Manual Acquisition','Units','normalized',...
                'Position',[0 currentheight 0.5 2*height2]);

txtWelcomeAlign = uicontrol(panelManAcquire,'Tag','txtWelcomeAlign',...
                'Style','text','Units','normalized',...
                'String','5) Use Instrument Tab & preview to locate the upper right spot of array.',...
                'HorizontalAlignment','Left','Background',color.bgc{1},...
                'Position',[0.02 0.4 0.96 0.58]);

btnWelcomeAcquire = uicontrol(panelManAcquire,'Tag','btnWelcomeAcquire',...
                'Style','pushbutton',...
                'String','6) Acquire Data','Units','normalized',...
                'Callback',@GUI_Callback_btnWelcome_Acquire,...
                'HorizontalAlignment','Left',...
                'Position',[0.02 0.02 0.96 0.32]);

panelAutoAcquire = uipanel(tabWelcome,...
                'Tag','panelAutoAcquire',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BorderType','line',...
                'BackgroundColor',color.bgc{2},...
                'Title','Automatic Acquisition','Units','normalized',...
                'Position',[0.55 currentheight 0.45 2*height2]);

btnWelcomeAutoAcquire = uicontrol(panelAutoAcquire,'Tag','btnWelcomeAutoAcquire',...
                'Style','pushbutton',...
                'String','5/6) Acquire Data','Units','normalized',...
                'Callback',@GUI_Callback_btnWelcome_AutoAcquire,...
                'HorizontalAlignment','Left',...
                'Position',[0.02 0.35 0.96 0.32]);
currentheight = currentheight - height2;
            
btnWelcomeUnloadChip = uicontrol(tabWelcome,'Tag','btnWelcomeUnloadChip',...
                'Style','pushbutton',...
                'String','7) Unload Chip','Units','normalized',...
                'Callback',@GUI_Callback_btnWelcome_UnloadChip,...
                'HorizontalAlignment','Left',...
                'Position',[centerbtn currentheight widthbtn2 height1]);
currentheight = currentheight - height2;

btnWelcomeStop = uicontrol(tabWelcome,'Tag','btnWelcomeStop',...
                'Style','pushbutton','Enable','off',...
                'String','Stop Acquisition','Units','normalized',...
                'Background',color.bgc{5},...
                'Callback',@GUI_Callback_btnWelcome_Stop,...
                'HorizontalAlignment','Left',...
                'Position',[centerbtn currentheight widthbtn2 height1]);

btnWelcomeVersionLog = uicontrol(tabWelcome,'Tag','btnWelcomeVersionLog','Style','pushbutton',...
                'String','Version Log','Units','normalized',...
                'Callback',@GUI_Callback_btnWelcome_OpenVersionLog,...
                'Position',[centerbtn 0.05 widthbtn2 height1]);

%% TAB ChipInfo
currentheight = reset;

txtChipInfo = uicontrol(tabChipInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Enter the sample information.','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight widthtotal height3]);
currentheight = currentheight - 0.8*height2;

GUI_makeGUI_BrowseAndTxtBox(tabChipInfo,'SaveFolder',...
                'Save Folder','Save Path',currentheight,...
                @GUI_Callback_btnSaveFolder,@GUI_Callback_editSaveFolder)
currentheight = currentheight - 0.6*height1;

% btnScanBarcode = uicontrol(tabChipInfo,'Tag','btnScanBarcode','Style','pushbutton',...
%                 'String','Scan Barcode','Units','normalized',...
%                 'Callback',@GUI_Callback_btnScanBarcode,...
%                 'Visible','off',...
%                 'Position',[centerbtn currentheight widthbtn2 height1]);
% currentheight = currentheight - height1;

txtChipID = uicontrol(tabChipInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Chip ID:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight-0.005 widthleft height3]);
editChipID = uicontrol(tabChipInfo,'Style','edit',...
                'Tag','editChipID',...
                'BackgroundColor',color.bgc{1},...
                'String','Enter Chip ID','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[rightX currentheight rightXwidth height3]);
currentheight = currentheight - 1.1*height3;

txtChipType = uicontrol(tabChipInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Chip Type:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[0.5 currentheight-0.005 0.25 height3]);
popupChipType = uicontrol(tabChipInfo,'Tag','popupChipType','Style','popupmenu',...
                'String',{''},'Units','normalized',...
                'BackgroundColor',color.bgc{1},...
                'Callback',@GUI_Callback_popupChipType,...
                'Position',[0.75 currentheight 0.2 height3]);
            
radPrescan = uicontrol(tabChipInfo,'Style','radiobutton',...
                'Tag','radPrescan',...
                'String','Pre Scan','Units','normalized',...
                'HorizontalAlignment','Left',...
                'BackgroundColor',color.bgc{2},...
                'Callback',@GUI_Callback_radPrescan,...
                'Position',[leftX currentheight width height3]);
currentheight = currentheight - height3;

radPostscan = uicontrol(tabChipInfo,'Style','radiobutton',...
                'Tag','radPostscan',...
                'String','Post Scan','Units','normalized',...
                'HorizontalAlignment','Left',...
                'BackgroundColor',color.bgc{2},...
                'Callback',@GUI_Callback_radPostscan,...
                'Position',[leftX currentheight width height3]);
currentheight = currentheight - 1.1*height2;

panelArrayInfo = uipanel(tabChipInfo,...
                'Tag','panelArrayInfo',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BorderType','line',...
                'BackgroundColor',color.bgc{2},...
                'Title','Array Info','Units','normalized',...
                'Position',[panelLeftX currentheight panelWidth 1.1*height2]);
panelheight = 0.8;
panelheight1 = 0.35;
panelheight2 = 0.35;

txtWidth = uicontrol(panelArrayInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Width','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX2 panelheight thirdwidth2 0.8*panelheight1]);
            
txtHeight = uicontrol(panelArrayInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Height','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX3 panelheight thirdwidth2 0.8*panelheight1]);
panelheight = panelheight - panelheight1;

txtArraySize = uicontrol(panelArrayInfo,'Style','text',...
                'Tag','txtArraySize',...
                'BackgroundColor',color.bgc{2},...
                'String','Array Size:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight thirdwidth panelheight1]);
editArrayX = uicontrol(panelArrayInfo,'Style','edit',...
                'Tag','editArrayX',...
                'BackgroundColor',color.bgc{1},...
                'String','X','Units','normalized',...
                'Callback',@GUI_Callback_editArrayX,...
                'HorizontalAlignment','Center',...
                'Position',[thirdX2 panelheight thirdwidth2 panelheight1]);
editArrayY = uicontrol(panelArrayInfo,'Style','edit',...
                'Tag','editArrayY',...
                'BackgroundColor',color.bgc{1},...
                'String','Y','Units','normalized',...
                'Callback',@GUI_Callback_editArrayY,...
                'HorizontalAlignment','Center',...
                'Position',[thirdX3 panelheight thirdwidth2 panelheight1]);
panelheight = panelheight - 1.1*panelheight2;

txtArrayPitch = uicontrol(panelArrayInfo,'Style','text',...
                'Tag','txtArrayDistance',...
                'BackgroundColor',color.bgc{2},...
                'String','Spot pitch:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight thirdwidth panelheight1]);
editPitchX = uicontrol(panelArrayInfo,'Style','edit',...
                'Tag','editArrayPitchX',...
                'BackgroundColor',color.bgc{1},...
                'String','X','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX2 panelheight thirdwidth2 panelheight1]);
editPitchY = uicontrol(panelArrayInfo,'Style','edit',...
                'Tag','editArrayPitchY',...
                'BackgroundColor',color.bgc{1},...
                'String','Y','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX3 panelheight thirdwidth2 panelheight1]);
currentheight = currentheight - 1.3*height2;

panelParticleInfo = uipanel(tabChipInfo,...
                'Tag','panelParticleInfo',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BorderType','line',...
                'BackgroundColor',color.bgc{2},...
                'Title','Particle Info','Units','normalized',...
                'Position',[panelLeftX currentheight panelWidth 1.2*height2]);
panelheight = 0.70;
panelheight1 = 0.35;
panelheight2 = 0.35;

txtPType = uicontrol(panelParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Type:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight-0.1 thirdwidth 0.9*panelheight1]);

popupSelectParticle = uicontrol(panelParticleInfo,'Tag','popupSelectParticle','Style','popupmenu',...
                'Callback',@GUI_Callback_popupSelectParticle,...
                'String',{'None'},'Units','normalized',...
                'BackgroundColor',color.bgc{1},...
                'Position',[thirdX2 panelheight 0.5 0.9*panelheight1]);
panelheight = panelheight - 1.1*panelheight2;

txtMinHist = uicontrol(panelParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Min','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX2 panelheight thirdwidth2 0.9*panelheight1]);
            
txtMaxHist = uicontrol(panelParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Max','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX3 panelheight thirdwidth2 0.9*panelheight1]);
panelheight = panelheight - 0.85*panelheight1;

txtPSize = uicontrol(panelParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Size:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight thirdwidth panelheight1]);
editMinHist = uicontrol(panelParticleInfo,'Style','edit',...
                'Tag','editMinHist',...
                'BackgroundColor',color.bgc{1},...
                'String','X','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Callback',@GUI_Callback_editMinHist,...
                'Position',[thirdX2 panelheight thirdwidth2 panelheight1]);
editMaxHist = uicontrol(panelParticleInfo,'Style','edit',...
                'Tag','editMaxHist',...
                'BackgroundColor',color.bgc{1},...
                'String','Y','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Callback',@GUI_Callback_editMaxHist,...
                'Position',[thirdX3 panelheight thirdwidth2 panelheight1]);
currentheight = currentheight - 1.6*height2;

panelRefParticleInfo = uipanel(tabChipInfo,...
                'Tag','panelRefParticleInfo',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BorderType','line',...
                'BackgroundColor',color.bgc{2},...
                'Title','Reference Particle Info','Units','normalized',...
                'Position',[panelLeftX currentheight panelWidth 1.5*height2]);
panelheight = 0.8;
panelheight1 = 0.25;
panelheight2 = 0.35;

chkRefParticle = uicontrol(panelRefParticleInfo,'Tag','chkRefParticle',...
                'Style','checkbox','Value',1,...
                'Callback',@GUI_Callback_chkRefParticle,...
                'BackgroundColor',color.bgc{2},...
                'String','Enable','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX2 panelheight thirdwidth 0.9*panelheight1]);
panelheight = panelheight - panelheight1;
            
txtPType = uicontrol(panelRefParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Type:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight-0.1 thirdwidth 0.9*panelheight1]);

popupSelectRefParticle = uicontrol(panelRefParticleInfo,'Tag','popupSelectRefParticle','Style','popupmenu',...
                'Callback',@GUI_Callback_popupSelectRefParticle,...
                'String',{'None'},'Units','normalized',...
                'BackgroundColor',color.bgc{1},...
                'Position',[thirdX2 panelheight 0.5 0.9*panelheight1]);
panelheight = panelheight - 0.9*panelheight2;

txtMinHist = uicontrol(panelRefParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Min','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX2 panelheight thirdwidth2 0.9*panelheight1]);
            
txtMaxHist = uicontrol(panelRefParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Max','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX3 panelheight thirdwidth2 0.9*panelheight1]);
panelheight = panelheight - 0.85*panelheight1;

txtPSize = uicontrol(panelRefParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Size:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight thirdwidth panelheight1]);
editRefMinHist = uicontrol(panelRefParticleInfo,'Style','edit',...
                'Tag','editRefMinHist',...
                'BackgroundColor',color.bgc{1},...
                'String','X','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Callback',@GUI_Callback_editRefMinHist,...
                'Position',[thirdX2 panelheight thirdwidth2 panelheight1]);
editRefMaxHist = uicontrol(panelRefParticleInfo,'Style','edit',...
                'Tag','editRefMaxHist',...
                'BackgroundColor',color.bgc{1},...
                'String','Y','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Callback',@GUI_Callback_editRefMaxHist,...
                'Position',[thirdX3 panelheight thirdwidth2 panelheight1]);
currentheight = currentheight - 0.7*height2;

txtComment = uicontrol(tabChipInfo,'Style','text',...
                'Tag','txtComment',...
                'BackgroundColor',color.bgc{2},...
                'String','Comments','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 currentheight thirdwidth 1.4*height3]);

editComment = uicontrol(tabChipInfo,'Style','edit',...
                'Tag','editComment',...
                'BackgroundColor',color.bgc{1},...
                'String','','Units','normalized',...
                'Min',1,'Max',50,...
                'HorizontalAlignment','Left',...
                'Position',[leftX 0.05 widthtotal currentheight-1.5*height3]);

%% TAB HardwareCtrl
currentheight = reset;

% currentheight = currentheight - height1;
panelInstrument = uipanel(tabHardwareCtrl,...
                'Tag','panelInstrument',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BorderType','line',...
                'BackgroundColor',color.bgc{2},...
                'Title','Instrument','Units','normalized',...
                'Position',[panelLeftX currentheight panelWidth 0.75*height1]);
txtInstrumentName = uicontrol(panelInstrument,'Style','text',...
                'Tag','txtInstrumentName',...
                'BackgroundColor',color.bgc{2},...
                'String','Filler','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[leftX 0.05 0.9 0.9]);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
currentheight = currentheight - (2.2*height2);

panelCameraCtrl = uipanel(tabHardwareCtrl,...
                'Tag','panelCameraCtrl',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BorderType','line',...
                'BackgroundColor',color.bgc{2},...
                'Title','Camera Controls','Units','normalized',...
                'Position',[panelLeftX currentheight panelWidth 2*height2]);
panelheight = 0.82;
panelheight1 = 0.17;
panelheight2 = 0.19;

popupSelectCamera = uicontrol(panelCameraCtrl,'Tag','popupSelectCamera','Style','popupmenu',...
                'String',{'None'},'Units','normalized',...
                'BackgroundColor',color.bgc{1},...
                'Callback',@GUI_Callback_popupSelectCamera,...
                'Position',[leftX panelheight 0.8 panelheight1]);
panelheight = panelheight - (panelheight2+0.05);

txtScanExposure = uicontrol(panelCameraCtrl,'Style','text',...
                'Tag','txtScanExposure',...
                'BackgroundColor',color.bgc{2},...
                'String','Exposure time[ms]:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX panelheight-txtOffset 1.8*thirdwidth panelheight1]);
editScanExposure = uicontrol(panelCameraCtrl,'Tag','editScanExposure','Style','edit',...
                'String','#','Units','normalized',...
                'Callback',@GUI_Callback_editScanExposure,...
                'BackgroundColor',color.bgc{1},...
                'Position',[thirdX3 panelheight thirdwidth2 panelheight1]);
panelheight = panelheight - panelheight2;

txtScanAvg = uicontrol(panelCameraCtrl,'Style','text',...
                'Tag','txtScanAvg',...
                'BackgroundColor',color.bgc{2},...
                'String','Frames to Average:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX panelheight-txtOffset 1.8*thirdwidth panelheight1]);
editScanAvg = uicontrol(panelCameraCtrl,'Tag','editScanAvg','Style','edit',...
                'String','#','Units','normalized',...
                'BackgroundColor',color.bgc{1},...
                'Position',[thirdX3 panelheight thirdwidth2 panelheight1]);
panelheight = panelheight - panelheight2;

txtScanROI = uicontrol(panelCameraCtrl,'Style','text',...
                'Tag','txtScanROI',...
                'BackgroundColor',color.bgc{2},...
                'String','Width x Height:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX panelheight 0.35 panelheight1]);
editScanROIX = uicontrol(panelCameraCtrl,'Tag','editScanROIX','Style','edit',...
                'String','X','Units','normalized',...
                'Callback',@GUI_Callback_editScanROIX,...
                'BackgroundColor',color.bgc{1},...
                'Position',[0.5 panelheight 0.2 panelheight1]);
editScanROIY = uicontrol(panelCameraCtrl,'Tag','editScanROIY','Style','edit',...
                'String','Y','Units','normalized',...
                'Callback',@GUI_Callback_editScanROIY,...
                'BackgroundColor',color.bgc{1},...
                'Position',[0.75 panelheight 0.2 panelheight1]);
panelheight = panelheight - panelheight2;

txtScanOffset = uicontrol(panelCameraCtrl,'Style','text',...
                'Tag','txtScanOffset',...
                'BackgroundColor',color.bgc{2},...
                'String','Offsets:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX panelheight 0.35 panelheight1]);
editScanOffsetX = uicontrol(panelCameraCtrl,'Tag','editScanOffsetX','Style','edit',...
                'String','Width','Units','normalized',...
                'Callback',@GUI_Callback_editScanOffsetX,...
                'BackgroundColor',color.bgc{1},...
                'Position',[0.5 panelheight 0.2 panelheight1]);
editScanOffsetY = uicontrol(panelCameraCtrl,'Tag','editScanOffsetY','Style','edit',...
                'String','Height','Units','normalized',...
                'Callback',@GUI_Callback_editScanOffsetY,...
                'BackgroundColor',color.bgc{1},...
                'Position',[0.75 panelheight 0.2 panelheight1]);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
currentheight = currentheight - height1;

panelLEDCtrl = uibuttongroup(tabHardwareCtrl,...
                'Tag','panelLEDCtrl',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BorderType','line',...
                'BackgroundColor',color.bgc{2},...
                'Title','LED Controls','Units','normalized',...
                'Position',[panelLeftX currentheight panelWidth 0.75*height1]);
panelheight = 0.05;

radioLED1 = uicontrol(panelLEDCtrl,'Style','radiobutton',...
                'Tag','radioLED1',...
                'String','Red','Units','normalized',...
                'HorizontalAlignment','Left',...
                'BackgroundColor',color.bgc{2},...
                'Position',[leftX panelheight width 0.9]);

radioLED2 = uicontrol(panelLEDCtrl,'Style','radiobutton',...
                'Tag','radioLED2',...
                'String','Green','Units','normalized',...
                'HorizontalAlignment','Left',...
                'BackgroundColor',color.bgc{2},...
                'Position',[leftX+0.2 panelheight width 0.9]);
            
radioLED3 = uicontrol(panelLEDCtrl,'Style','radiobutton',...
                'Tag','radioLED3',...
                'String','Amber','Units','normalized',...
                'HorizontalAlignment','Left',...
                'BackgroundColor',color.bgc{2},...
                'Position',[leftX+0.45 panelheight width 0.9]);

radioLED4 = uicontrol(panelLEDCtrl,'Style','radiobutton',...
                'Tag','radioLED4',...
                'String','Blue','Units','normalized',...
                'HorizontalAlignment','Left',...
                'BackgroundColor',color.bgc{2},...
                'Position',[leftX+0.7 panelheight 0.2 0.9]);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
currentheight = currentheight - 0.17;

panelFocusCtrl = uipanel(tabHardwareCtrl,...
                'Tag','panelFocusCtrl',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BorderType','line',...
                'BackgroundColor',color.bgc{2},...
                'Title','Focus Controls','Units','normalized',...
                'Position',[panelLeftX  currentheight panelWidth 0.15]);
panelheight = 0.7;

panelCornerCtrl = uibuttongroup(panelFocusCtrl,...
                'Tag','panelCornerCtrl',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BorderType','line',...
                'BackgroundColor',color.bgc{2},...
                'Title','# of Points','Units','normalized',...
                'Position',[leftX panelheight widthtotal 0.3]);
            
rad3Corner = uicontrol(panelCornerCtrl,'Style','radiobutton',...
                'Tag','rad3Corner',...
                'String','Full','Units','normalized',...
                'HorizontalAlignment','Left',...
                'BackgroundColor',color.bgc{2},...
                'Position',[leftX 0.05 0.5 0.95]);

rad4Corner = uicontrol(panelCornerCtrl,'Style','radiobutton',...
                'Tag','rad4Corner',...
                'String','Z-only','Units','normalized',...
                'HorizontalAlignment','Left',...
                'BackgroundColor',color.bgc{2},...
                'Position',[centerX 0.05 0.5 0.95]);
panelheight = panelheight - 0.3;
 
btnAutofocus = uicontrol(panelFocusCtrl,'Tag','btnAutofocus','Style','pushbutton',...
                'String','Focus Image','Units','normalized',...
                'Callback',@GUI_Callback_btnAutofocus,...
                'Position',[0.05 panelheight 0.42 0.25]);

btnFocusPlane = uicontrol(panelFocusCtrl,'Style','pushbutton',...
                'Tag','btnFocusPlane',...
                'String','Calibrate and Scan Array','Units','normalized',...
                'Callback',@GUI_Callback_btnFocusPlane,...
                'Position',[0.53 panelheight 0.42 0.25]);
panelheight = panelheight - 0.3;
            
btnPreview = uicontrol(panelFocusCtrl,'Tag','btnPreview',...
                'Style','pushbutton',...
                'String','Open Preview','Units','normalized',...
                'Callback',@GUI_Callback_btnPreview,...
                'HorizontalAlignment','Left',...
                'Position',[0.05 panelheight 0.42 0.25]);
            
btnPreviewClose = uicontrol(panelFocusCtrl,'Tag','btnPreviewClose',...
                'Style','pushbutton',...
                'String','Close Preview','Units','normalized',...
                'Callback',@GUI_Callback_btnClosePreview,...
                'HorizontalAlignment','Left',...
                'Position',[0.53 panelheight 0.42 0.25]);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
currentheight = currentheight - 0.47;

panelStageCtrl = uipanel(tabHardwareCtrl,...
                'Tag','panelStageCtrl',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BorderType','line',...
                'BackgroundColor',color.bgc{2},...
                'Title','Stage Controls','Units','normalized',...
                'Position',[panelLeftX currentheight panelWidth 0.45]);

panelZAxis = uipanel(panelStageCtrl,...
                'Tag','panelZAxis',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BorderType','line',...
                'BackgroundColor',color.bgc{2},...
                'Title','Z Axis','Units','normalized',...
                'Position',[panelLeftX 0.75 panelWidth 0.25]);
panelheight = 0.75;

txtZAxisPos = uicontrol(panelZAxis,'Style','text',...
                'Tag','txtZAxisPos',...
                'BackgroundColor',color.bgc{2},...
                'String','Pos [um]:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight-0.005 widthleft 0.25]);
editZPos = uicontrol(panelZAxis,'Tag','editZPos','Style','edit',...
                'String','#','Units','normalized',...
                'Callback',@GUI_Callback_editZPos,...
                'BackgroundColor',color.bgc{1},...
                'Position',[0.28 panelheight 0.25 0.25]);
btnZUp = uicontrol(panelZAxis,'Tag','btnZUp','Style','pushbutton',...
                'String','Z+','Units','normalized',...
                'Callback',@GUI_Callback_btnMoveZUp,...
                'Position',[thirdX3 panelheight-0.05 thirdwidth 0.3]);
panelheight = panelheight - 0.35;

txtZAxisStep = uicontrol(panelZAxis,'Style','text',...
                'Tag','txtZAxisStep',...
                'BackgroundColor',color.bgc{2},...
                'String','Step [um]:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight-0.005 widthleft 0.25]);
editZStep = uicontrol(panelZAxis,'Tag','editZStep','Style','edit',...
                'String','#','Units','normalized',...
                'Callback',@GUI_Callback_editZStep,...
                'BackgroundColor',color.bgc{1},...
                'Position',[0.28 panelheight 0.25 0.25]);
btnZDown = uicontrol(panelZAxis,'Tag','btnZDown','Style','pushbutton',...
                'String','Z-','Units','normalized',...
                'Callback',@GUI_Callback_btnMoveZDown,...
                'Position',[thirdX3 panelheight-0.05 thirdwidth 0.3]);
panelheight = panelheight - 0.35;

txtEncoder = uicontrol(panelZAxis,'Style','text',...
                'Tag','txtZAxisStep',...
                'BackgroundColor',color.bgc{2},...
                'String','Encoder:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight-0.005 widthleft 0.25]);
txtEncoderReadout = uicontrol(panelZAxis,'Style','text',...
                'Tag','txtEncoderReadout',...
                'BackgroundColor',color.bgc{1},...
                'String','#','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[0.28 panelheight 0.25 0.25]);
txtZVelocity = uicontrol(panelZAxis,'Style','text',...
                'Tag','txtZVelocity',...
                'BackgroundColor',color.bgc{2},...
                'String','Velocity:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[0.55 panelheight-0.005 0.25 0.25]);
editZVelocity = uicontrol(panelZAxis,'Tag','editZVelocity','Style','edit',...
                'String','#','Units','normalized',...
                'Callback',@GUI_Callback_editZVelocity,...
                'BackgroundColor',color.bgc{1},...
                'Position',[0.78 panelheight 0.2 0.25]);
            
panelXYAxis = uipanel(panelStageCtrl,...
                'Tag','panelXYAxis',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BorderType','line',...
                'BackgroundColor',color.bgc{2},...
                'Title','XY Axis','Units','normalized',...
                'Position',[panelLeftX 0.05 panelWidth 0.68]);
panelheight = 0.94;

txtXYPos = uicontrol(panelXYAxis,'Style','text',...
                'Tag','txtXYPos',...
                'BackgroundColor',color.bgc{2},...
                'String','Position[um]','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[0.5 panelheight widthleft 0.06]);
panelheight = panelheight - 0.065;

txtXYPos2 = uicontrol(panelXYAxis,'Style','text',...
                'Tag','txtXYPos2',...
                'BackgroundColor',color.bgc{2},...
                'String','     X             Y','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[0.45 panelheight 0.35 0.06]);
panelheight = panelheight - 0.1;

editXPos = uicontrol(panelXYAxis,'Tag','editXPos','Style','edit',...
                'String','X','Units','normalized',...
                'Callback',@GUI_Callback_editXPos,...
                'BackgroundColor',color.bgc{1},...
                'Position',[0.45 panelheight 0.2 0.085]);
editYPos = uicontrol(panelXYAxis,'Tag','editYPos','Style','edit',...
                'String','Y','Units','normalized',...
                'Callback',@GUI_Callback_editYPos,...
                'BackgroundColor',color.bgc{1},...
                'Position',[0.7 panelheight 0.2 0.085]);

imageAxis = axes('Parent',panelXYAxis,...
                 'Tag','imageAxis',...
                 'HitTest','off',...
                 'DataAspectRatioMode','auto',...
                 'Position',[0.05 panelheight 0.23 0.23]);
icon = imread('STAGE_axis.png'); imshow(icon);
panelheight = panelheight - 0.1;

chkSmartMove = uicontrol(panelXYAxis,'Tag','chkSmartMove',...
                'Style','checkbox','Value',0,...
                'String','Smart Move','Units','normalized',...
                'BackgroundColor',color.bgc{2},...
                'HorizontalAlignment','Left',...
                'Position',[panelLeftX panelheight 0.4  0.085]);

txtXYVelocity = uicontrol(panelXYAxis,'Style','text',...
                'Tag','txtZAxisStep',...
                'BackgroundColor',color.bgc{2},...
                'String','Velocity:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[0.55 panelheight-0.005 0.25 0.085]);
editXYVelocity = uicontrol(panelXYAxis,'Tag','editXYVelocity','Style','edit',...
                'String','#','Units','normalized',...
                'Callback',@GUI_Callback_editXYVelocity,...
                'BackgroundColor',color.bgc{1},...
                'Position',[0.78 panelheight 0.2 0.085]);
panelheight = panelheight - 0.1;
            
txtXYStep = uicontrol(panelXYAxis,'Style','text',...
                'Tag','txtXYStep',...
                'BackgroundColor',color.bgc{2},...
                'String','Step:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[0.55 panelheight-0.005 0.25 0.085]);
editXYStep = uicontrol(panelXYAxis,'Tag','editXYStep','Style','edit',...
                'String','#','Units','normalized',...
                'Callback',@GUI_Callback_editXYStep,...
                'BackgroundColor',color.bgc{1},...
                'Position',[0.78 panelheight 0.2 0.085]);
panelheight = panelheight - 0.25;

panelMoveType = uibuttongroup(panelXYAxis,...
                'Tag','panelMoveType',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BorderType','line',...
                'BackgroundColor',color.bgc{2},...
                'Title','Move Type','Units','normalized',...
                'Position',[leftX panelheight 0.28 0.32]);

radUser = uicontrol(panelMoveType,'Style','radiobutton',...
                'Tag','radUser',...
                'String','User','Units','normalized',...
                'HorizontalAlignment','Left',...
                'BackgroundColor',color.bgc{2},...
                'Position',[0 0.67 1 0.3]);

radFOV = uicontrol(panelMoveType,'Style','radiobutton',...
                'Tag','radFOV',...
                'String','FOV','Units','normalized',...
                'HorizontalAlignment','Left',...
                'BackgroundColor',color.bgc{2},...
                'Position',[0 0.34 1 0.3]);

radPitch = uicontrol(panelMoveType,'Style','radiobutton',...
                'Tag','radPitch',...
                'String','Pitch','Units','normalized',...
                'HorizontalAlignment','Left',...
                'BackgroundColor',color.bgc{2},...
                'Position',[0 0.01 1 0.3]);
panelheight = panelheight - 0.07;

btnMoveYUp = uicontrol(panelXYAxis,'Tag','btnMoveYUp','Style','pushbutton',...
                'String','Y+','Units','normalized',...
                'Callback',@GUI_Callback_btnMoveYUp,...
                'Position',[0.57 panelheight+0.15 0.2 0.15]);
btnMoveYDown = uicontrol(panelXYAxis,'Tag','btnMoveYDown','Style','pushbutton',...
                'String','Y-','Units','normalized',...
                'Callback',@GUI_Callback_btnMoveYDown,...
                'Position',[0.57 panelheight 0.2 0.15]);
btnMoveXRight = uicontrol(panelXYAxis,'Tag','btnMoveXRight','Style','pushbutton',...
                'String','X+','Units','normalized',...
                'Callback',@GUI_Callback_btnMoveXRight,...
                'Position',[0.77 panelheight 0.2 0.15]);
btnMoveXLeft = uicontrol(panelXYAxis,'Tag','btnMoveXLeft','Style','pushbutton',...
                'String','X-','Units','normalized',...
                'Callback',@GUI_Callback_btnMoveXLeft,...
                'Position',[0.37 panelheight 0.2 0.15]);
%% TAB Acquisition
currentheight = reset;

GUI_makeGUI_PopupAndChkBox(tabAcquisition,'Mirror','Mirror File',{'None'},...
                currentheight,@GUI_Callback_popupMirror,@GUI_Callback_chkUseMirror)
currentheight = currentheight - 0.05;

btnMirrorScan = uicontrol(tabAcquisition,'Tag','btnMirrorScan','Style','pushbutton',...
                'String','Mirror: Acquire','Units','normalized',...
                'Callback',@GUI_Callback_btnScanMirror,...
                'Position',[centerbtn currentheight widthbtn2 0.04]);
currentheight = currentheight - 0.88;

panelScan = uipanel(tabAcquisition,...
                'Tag','panelScan',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BorderType','line',...
                'BackgroundColor',color.bgc{2},...
                'Title','Dataset','Units','normalized',...
                'Position',[panelLeftX currentheight panelWidth 0.87]);
panelheight = 0.94;

btnPreview = uicontrol(panelScan,'Tag','btnPreview',...
                'Style','pushbutton',...
                'String','Open Preview','Units','normalized',...
                'Callback',@GUI_Callback_btnPreview,...
                'HorizontalAlignment','Left',...
                'Position',[centerbtn panelheight widthbtn2 0.06]);
panelheight = panelheight - 0.075;

btnPreviewClose = uicontrol(panelScan,'Tag','btnPreviewClose',...
                'Style','pushbutton',...
                'String','Close Preview','Units','normalized',...
                'Callback',@GUI_Callback_btnClosePreview,...
                'HorizontalAlignment','Left',...
                'Position',[centerbtn panelheight widthbtn2 0.06]);
panelheight = panelheight - 0.075;

btnPreviewArray = uicontrol(panelScan,'Tag','btnPreviewArray',...
                'Style','pushbutton',...
                'String','Array: Preview','Units','normalized',...
                'Callback',@GUI_Callback_btnPreviewArray,...
                'HorizontalAlignment','Left',...
                'Position',[centerbtn panelheight widthbtn2 0.06]);
panelheight = panelheight - 0.09;

GUI_makeGUI_SliderAndTxtBox(panelScan,'Dwell','Preview Dwell Time',...
                'Seconds',0.01,10,1,panelheight,...
                @GUI_Callback_sldDwell,@GUI_Callback_editDwell);
panelheight = panelheight - 0.04;

btnArrayAdjust = uicontrol(panelScan,'Tag','btnArrayAdjust',...
                'Style','pushbutton',...
                'String','Array: Adjust','Units','normalized',...
                'Callback',@GUI_Callback_btnArrayAdjust,...
                'Position',[centerbtn panelheight widthbtn2 0.06]);
panelheight = panelheight - 0.075;

btnScanArray = uicontrol(panelScan,'Tag','btnScanArray',...
                'Style','pushbutton',...
                'String','Array: Acquire','Units','normalized',...
                'Callback',@GUI_Callback_btnWelcome_Acquire,...
                'HorizontalAlignment','Left',...
                'Position',[centerbtn panelheight widthbtn2 0.06]);
panelheight = panelheight - 0.075;

btnDefocusScan = uicontrol(panelScan,'Tag','btnDefocusScan',...
                'Style','pushbutton',...
                'String','Spot: Acquire','Units','normalized',...
                'Callback',@GUI_Callback_btnDefocusScan,...
                'HorizontalAlignment','Left',...
                'Position',[centerbtn panelheight widthbtn2 0.06]);
panelheight = panelheight - 0.075;

btnScanSpot = uicontrol(panelScan,'Tag','btnScanSpot',...
                'Style','pushbutton',...
                'String','Save Image','Units','normalized',...
                'Callback',@GUI_Callback_btnScanSpot,...
                'HorizontalAlignment','Left',...
                'Position',[centerbtn panelheight widthbtn2 0.06]);
panelheight = panelheight - 0.075;

btnImgHist = uicontrol(panelScan,'Tag','btnImgHist',...
                'Style','pushbutton',...
                'String','Hist: Image Intensity','Units','normalized',...
                'Callback',@GUI_Callback_btnHist_Image,...
                'HorizontalAlignment','Left',...
                'Position',[centerbtn panelheight widthbtn2 0.06]);
panelheight = panelheight - 0.075;

btnSizeHist = uicontrol(panelScan,'Tag','btnSizeHist',...
                'Style','pushbutton',...
                'String','Hist: Particle Size','Units','normalized',...
                'Callback',@GUI_Callback_btnHist_ParticleSize,...
                'HorizontalAlignment','Left',...
                'Position',[centerbtn panelheight widthbtn2 0.06]);
panelheight = panelheight - 0.075;

btnIntHist = uicontrol(panelScan,'Tag','btnIntHist',...
                'Style','pushbutton',...
                'String','Hist: Particle Contrast','Units','normalized',...
                'Callback',@GUI_Callback_btnHist_ParticleContrast,...
                'HorizontalAlignment','Left',...
                'Position',[centerbtn panelheight widthbtn2 0.06]);
panelheight = panelheight - 0.075;

btnTakeMinimap = uicontrol(panelScan,'Tag','btnTakeMinimap','Style','pushbutton',...
                'String','Calibrate Smartmove Plane','Units','normalized',...
                'Callback',@GUI_Callback_btnPlane_Calibration,...
                'Position',[centerbtn panelheight widthbtn2 0.06]);
panelheight = panelheight - 0.075;

btnSaveMinimap = uicontrol(panelScan,'Tag','btnSaveMinimap',...
                'Style','pushbutton',...
                'String','Z-Stack: Calibrate/Save','Units','normalized',...
                'Callback',@GUI_Callback_btnSaveZstack,...
                'HorizontalAlignment','Left',...
                'Position',[centerbtn panelheight widthbtn2 0.06]);
panelheight = panelheight - 0.08;


%% TAB Process
currentheight = 0.9;

txtProcess = uicontrol(tabProcess,'Style','text',...
                'Tag','txtProcess',...
                'BackgroundColor',color.bgc{2},...
                'String','To process a dataset, select the dataset, define parameters, then click Particle Finder above the image.','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight widthtotal height1]);
currentheight = currentheight - 3.5*height1;

panelDataSet = uipanel(tabProcess,...
                'Tag','panelDataSet',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BorderType','line',...
                'BackgroundColor',color.bgc{2},...
                'Title','Dataset','Units','normalized',...
                'Position',[panelLeftX currentheight panelWidth 3*height1]);
panelheight1 = 0.18;
space = 1.2*panelheight1;
panelheight = 1 - panelheight1;

btnDataset = uicontrol(panelDataSet,'Style','pushbutton',...
                'String','Folder Browse','Units','normalized',...
                'Tag','btnDataset',...
                'HorizontalAlignment','Left',...
                'Callback',@GUI_Callback_btnSaveFolder,...
                'Position',[thirdX1 panelheight widthleft panelheight1]);
popupFiles = uicontrol(panelDataSet,'Tag','popupFiles','Style','popupmenu',...
                'String',{'none'},'Units','normalized',...
                'Callback',@GUI_Callback_popupFiles,...
                'Position',[rightX2 panelheight widthright panelheight1]);
panelheight = panelheight - space;

txtSelectPrescan = uicontrol(panelDataSet,'Style','text',...
                'Tag','txtSelectPrescan',...
                'BackgroundColor',color.bgc{2},...
                'String','Prescan File:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight widthleft panelheight1]);

popupSelectPrescan = uicontrol(panelDataSet,'Tag','popupSelectPrescan',...
                'Style','popupmenu','String',{'none'},...
                'Units','normalized','BackgroundColor',color.bgc{1},...
                'Callback',@GUI_Callback_popupSelectPrescan,...
                'Position',[rightX2  panelheight widthright panelheight1]);
panelheight = panelheight - space;

txtSelectPostscan = uicontrol(panelDataSet,'Style','text',...
                'Tag','txtSelectPostscan',...
                'BackgroundColor',color.bgc{2},...
                'String','Postscan File:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight widthleft panelheight1]);

popupSelectPostscan = uicontrol(panelDataSet,'Tag','popupSelectPostscan',...
                'Style','popupmenu','String',{'none'},...
                'Units','normalized','BackgroundColor',color.bgc{1},...
                'Callback',@GUI_Callback_popupSelectPostscan,...
                'Position',[rightX2  panelheight widthright panelheight1]);
panelheight = panelheight - 0.8*space;

txtDataType = uicontrol(panelDataSet,'Style','text',...
                'String','Mirror File','Units','normalized',...
                'HorizontalAlignment','Left',...
                'BackgroundColor',color.bgc{2},...
                'Position',[thirdX1 panelheight 0.6 0.8*panelheight1]);

chkEnabled= uicontrol(panelDataSet,'Tag','chkEnabledMirror',...
                'Style','checkbox','Value',1,...
                'Callback',@GUI_Callback_chkUseMirror,...
                'BackgroundColor',color.bgc{2},...
                'String','Enable','Units','normalized',...
                'HorizontalAlignment','Right',...
                'Position',[rightX2 panelheight 0.25 0.8*panelheight1]);
            
popupValue = uicontrol(panelDataSet,'Style','popupmenu',...
                'Tag','popupValueMirror',...
                'Callback',@GUI_Callback_popupMirror,...
                'String',{'none'},'Units','normalized',...
                'BackgroundColor',color.bgc{1},...
                'Position',[thirdX1 panelheight-0.5*panelheight1 0.9 0.5*panelheight1]);
currentheight = currentheight - 5.2*height1;

panelParams = uipanel(tabProcess,...
                'Tag','panelParams',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BorderType','line',...
                'BackgroundColor',color.bgc{2},...
                'Title','Detection Parameters','Units','normalized',...
                'Position',[panelLeftX currentheight panelWidth 5*height1]);
panelheight1 = 0.093;
space = 1.2*panelheight1;
panelheight = 1 - panelheight1;

txtInstr = uicontrol(panelParams,'Style','text',...
                'Tag','txtInstr',...
                'BackgroundColor',color.bgc{2},...
                'String','Instrument:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight widthleft panelheight1]);
popupFittingInstrument = uicontrol(panelParams,'Tag','popupFittingInstrument',...
                'Style','popupmenu','String',{'None'},...
                'Units','normalized','BackgroundColor',color.bgc{1},...
                'Position',[rightX2 panelheight widthright panelheight1]);
panelheight = panelheight - space;

txtMethod = uicontrol(panelParams,'Style','text',...
                'Tag','txtMethod',...
                'BackgroundColor',color.bgc{2},...
                'String','Fitting Method:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight widthleft panelheight1]);
popupFittingMethod = uicontrol(panelParams,'Tag','popupFittingMethod',...
                'Style','popupmenu','String',{'None'},...
                'Units','normalized','BackgroundColor',color.bgc{1},...
                'Position',[rightX2 panelheight widthright panelheight1]);
panelheight = panelheight - space;

txtIntensityTh = uicontrol(panelParams,'Style','text',...
                'Tag','txtIntensityThres',...
                'BackgroundColor',color.bgc{2},...
                'String','IntensityTh:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight widthleft panelheight1]);
editIntensityTh = uicontrol(panelParams,'Tag','editIntensityTh',...
                'Style','edit','String','0.5',...
                'Units','normalized','BackgroundColor',color.bgc{1},...
                'Position',[rightX2 panelheight widthright panelheight1]);
panelheight = panelheight - space;

txtEdgeTh = uicontrol(panelParams,'Style','text',...
                'Tag','txtEdgeTh',...
                'BackgroundColor',color.bgc{2},...
                'String','EdgeTh:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight widthleft panelheight1]);
editEdgeTh = uicontrol(panelParams,'Tag','editEdgeTh',...
                'Style','edit','String','2','Units','normalized',...
                'BackgroundColor',color.bgc{1},...
                'Position',[rightX2 panelheight widthright panelheight1]);
panelheight = panelheight - space;

txtTemplateSize = uicontrol(panelParams,'Style','text',...
                'Tag','txtTemplateSize',...
                'BackgroundColor',color.bgc{2},...
                'String','Template Size:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight widthleft panelheight1]);
editTemplateSize = uicontrol(panelParams,'Tag','editTemplateSize',...
                'Style','edit','String','9','Units','normalized',...
                'BackgroundColor',color.bgc{1},...
                'Position',[rightX2 panelheight widthright panelheight1]);
panelheight = panelheight - space;

txtSD = uicontrol(panelParams,'Style','text',...
                'Tag','txtSD',...
                'BackgroundColor',color.bgc{2},...
                'String','SD:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight widthleft panelheight1]);
editSD = uicontrol(panelParams,'Tag','editSD',...
                'Style','edit','String','1.5','Units','normalized',...
                'BackgroundColor',color.bgc{1},...
                'Position',[rightX2 panelheight widthright panelheight1]);
panelheight = panelheight - space;

txtGaussianTh = uicontrol(panelParams,'Style','text',...
                'Tag','txtGaussianTh',...
                'BackgroundColor',color.bgc{2},...
                'String','GaussianTh:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight widthleft panelheight1]);
editGaussianTh = uicontrol(panelParams,'Tag','editGaussianTh',...
                'Style','edit','String','0.7','Units','normalized',...
                'BackgroundColor',color.bgc{1},...
                'Position',[rightX2 panelheight widthright panelheight1]);
panelheight = panelheight - space;

txtInnerRadius = uicontrol(panelParams,'Style','text',...
                'Tag','txtInnerRadius',...
                'BackgroundColor',color.bgc{2},...
                'String','Inner Radius:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight widthleft panelheight1]);
editInnerRadius = uicontrol(panelParams,'Tag','editInnerRadius',...
                'Style','edit','String','9','Units','normalized',...
                'BackgroundColor',color.bgc{1},...
                'Position',[rightX2 panelheight widthright panelheight1]);
panelheight = panelheight - space;

txtOuterRadius = uicontrol(panelParams,'Style','text',...
                'Tag','txtInnerRadius',...
                'BackgroundColor',color.bgc{2},...
                'String','Outer Radius:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight widthleft panelheight1]);
editOuterRadius = uicontrol(panelParams,'Tag','editOuterRadius',...
                'Style','edit','String','12','Units','normalized',...
                'BackgroundColor',color.bgc{1},...
                'Position',[rightX2 panelheight widthright panelheight1]);
currentheight = currentheight - 2.4*height1;

panelProcessParticleInfo = uipanel(tabProcess,...
                'Tag','panelProcessParticleInfo',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BorderType','line',...
                'BackgroundColor',color.bgc{2},...
                'Title','Particle Info','Units','normalized',...
                'Position',[panelLeftX currentheight panelWidth 2.2*height1]);
panelheight1 = 0.22;
space = 1.2*panelheight1;
panelheight = 1 - panelheight1;

txtHistBins = uicontrol(panelProcessParticleInfo,'Style','text',...
                'Tag','txtHistBins',...
                'BackgroundColor',color.bgc{2},...
                'String','# of Bin:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight widthleft panelheight1]);
editHistBins = uicontrol(panelProcessParticleInfo,'Tag','editHistBins','Style','edit',...
                'String','20','Units','normalized',...
                'BackgroundColor',color.bgc{1},...
                'Position',[rightX2 panelheight widthright panelheight1]);
panelheight = panelheight - space;

txtPType = uicontrol(panelProcessParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Type:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight thirdwidth panelheight1]);

popupProcessSelectParticle = uicontrol(panelProcessParticleInfo,'Tag','popupProcessSelectParticle','Style','popupmenu',...
                'Callback',@GUI_Callback_popupProcessSelectParticle,...
                'String',{'none'},'Units','normalized',...
                'BackgroundColor',color.bgc{1},...
                'Position',[thirdX2 panelheight 0.5 panelheight1]);
panelheight = panelheight - space;

txtMinHist = uicontrol(panelProcessParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Min','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX2 panelheight thirdwidth2 0.9*panelheight1]);
            
txtMaxHist = uicontrol(panelProcessParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Max','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX3 panelheight thirdwidth2 0.9*panelheight1]);
panelheight = panelheight - 0.7*space;

txtPSize = uicontrol(panelProcessParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Size:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight thirdwidth panelheight1]);
editProcessMinHist = uicontrol(panelProcessParticleInfo,'Style','edit',...
                'Tag','editProcessMinHist',...
                'BackgroundColor',color.bgc{1},...
                'String','X','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Callback',@GUI_Callback_editProcessMinHist,...
                'Position',[thirdX2 panelheight thirdwidth2 panelheight1]);
editProcessMaxHist = uicontrol(panelProcessParticleInfo,'Style','edit',...
                'Tag','editProcessMaxHist',...
                'BackgroundColor',color.bgc{1},...
                'String','Y','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Callback',@GUI_Callback_editProcessMaxHist,...
                'Position',[thirdX3 panelheight thirdwidth2 panelheight1]);
currentheight = currentheight - 2.4*height1;

panelProcessRefParticleInfo = uipanel(tabProcess,...
                'Tag','panelProcessRefParticleInfo',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BorderType','line',...
                'BackgroundColor',color.bgc{2},...
                'Title','Reference Particle Info','Units','normalized',...
                'Position',[panelLeftX currentheight panelWidth 2.2*height1]);
panelheight1 = 0.22;
space = 1.2*panelheight1;
panelheight = 1 - panelheight1;

chkProcessRefParticle = uicontrol(panelProcessRefParticleInfo,'Tag','chkProcessRefParticle',...
                'Style','checkbox','Value',1,...
                'Callback',@GUI_Callback_chkProcessRefParticle,...
                'BackgroundColor',color.bgc{2},...
                'String','Enable','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX2 panelheight thirdwidth panelheight1]);
panelheight = panelheight - space;
            
txtPType = uicontrol(panelProcessRefParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Type:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight-0.1 thirdwidth panelheight1]);

popupProcessSelectRefParticle = uicontrol(panelProcessRefParticleInfo,'Tag','popupProcessSelectRefParticle',...
                'Style','popupmenu',...
                'Callback',@GUI_Callback_popupProcessSelectRefParticle,...
                'String',{'none'},'Units','normalized',...
                'BackgroundColor',color.bgc{1},...
                'Position',[thirdX2 panelheight 0.5 panelheight1]);
panelheight = panelheight - space;

txtMinHist = uicontrol(panelProcessRefParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Min','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX2 panelheight thirdwidth2 0.9*panelheight1]);
            
txtMaxHist = uicontrol(panelProcessRefParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Max','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX3 panelheight thirdwidth2 0.9*panelheight1]);
panelheight = panelheight - 0.7*space;

txtPSize = uicontrol(panelProcessRefParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Size:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight thirdwidth panelheight1]);
editProcessRefMinHist = uicontrol(panelProcessRefParticleInfo,'Style','edit',...
                'Tag','editProcessRefMinHist',...
                'BackgroundColor',color.bgc{1},...
                'String','X','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Callback',@GUI_Callback_editProcessRefMinHist,...
                'Position',[thirdX2 panelheight thirdwidth2 panelheight1]);
editProcessRefMaxHist = uicontrol(panelProcessRefParticleInfo,'Style','edit',...
                'Tag','editProcessRefMaxHist',...
                'BackgroundColor',color.bgc{1},...
                'String','Y','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Callback',@GUI_Callback_editProcessRefMaxHist,...
                'Position',[thirdX3 panelheight thirdwidth2 panelheight1]);
currentheight = currentheight - 1.2*height1;

btnRunSIFT = uicontrol(tabProcess,'Tag','btnProcessGUI',...
                'Style','pushbutton',...
                'String','Detect Particles','Units','normalized',...
                'Callback',@GUI_Callback_btnProcessGUI,...
                'HorizontalAlignment','Left',...
                'Position',[centerbtn currentheight widthbtn2 height1]);
% currentheight = currentheight - 0.22;
%  
% btnParticleHist = uicontrol(panelHist,'Tag','btnParticleHist',...
%                 'Style','pushbutton',...
%                 'String','Sizing Histogram','Units','normalized',...
%                 'Callback',@GUI_Callback_btnParticleHist,...
%                 'HorizontalAlignment','Left',...
%                 'Position',[centerbtn currentheight widthbtn2 panelheight2]);
% currentheight = currentheight - 3*height2;
%
%btnProcessGUI = uicontrol(tabProcess,'Tag','btnProcessGUI',...
%                'Style','pushbutton',...
%                'String','Launch Process GUI','Units','normalized',...
%                'Callback',@GUI_Callback_btnProcessGUI,...
%                'HorizontalAlignment','Left',...
%                'Position',[centerbtn currentheight widthbtn2 height1]);
            

%% TAB Options
% Lock unless the user inputs the correct password!
currentheight = reset;

txt1 = uicontrol(tabOptions,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Instrument Parameters',...
                'Units','normalized',...
                'FontWeight','Bold',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight 0.9 0.02]);
currentheight = currentheight - height3;

txtFOV = uicontrol(tabOptions,'Style','text',...
                'Tag','txtFOV',...
                'BackgroundColor',color.bgc{2},...
                'String','Field-of-view [um]: XX XX','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight widthbtn height3]);
currentheight = currentheight - height3;

txtEffPixel = uicontrol(tabOptions,'Style','text',...
                'Tag','txtEffPixel',...
                'BackgroundColor',color.bgc{2},...
                'String','Effective Pixel [um]: XX XX','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight widthbtn height3]);
currentheight = currentheight - height3;

txtDiffResolution = uicontrol(tabOptions,'Style','text',...
                'Tag','txtDiffResolution',...
                'BackgroundColor',color.bgc{2},...
                'String','Diffraction Resolution [um]: XX','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight widthbtn height3]);
currentheight = currentheight - height3;

txtPixel = uicontrol(tabOptions,'Style','text',...
                'Tag','txtPixel',...
                'BackgroundColor',color.bgc{2},...
                'String','Pixel Size [um]: XX XX','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight widthbtn height3]);
currentheight = currentheight - height3;

txtMag = uicontrol(tabOptions,'Style','text',...
                'Tag','txtMag',...
                'BackgroundColor',color.bgc{2},...
                'String','Magnification: XX','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight widthbtn height3]);
currentheight = currentheight - height3;

txtNA = uicontrol(tabOptions,'Style','text',...
                'Tag','txtNA',...
                'BackgroundColor',color.bgc{2},...
                'String','Numerical Aperture: XX','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight widthbtn height3]);
currentheight = currentheight - height3;

txtBitDepth = uicontrol(tabOptions,'Style','text',...
                'Tag','txtBitDepth',...
                'BackgroundColor',color.bgc{2},...
                'String','Camera Bitdepth: XX','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight widthbtn height3]);
currentheight = currentheight - height3;

txtFPS = uicontrol(tabOptions,'Style','text',...
                'Tag','txtFPS',...
                'BackgroundColor',color.bgc{2},...
                'String','Camera FPS: XX','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight widthbtn height3]);
currentheight = currentheight - height3;

txtMinExp = uicontrol(tabOptions,'Style','text',...
                'Tag','txtMinExp',...
                'BackgroundColor',color.bgc{2},...
                'String','Minimum Exposure [s]: XX','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight widthbtn height3]);
currentheight = currentheight - height3;

txtMaxExp = uicontrol(tabOptions,'Style','text',...
                'Tag','txtMaxExp',...
                'BackgroundColor',color.bgc{2},...
                'String','Maximum Exposure [s]: XX','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight widthbtn height3]);
currentheight = currentheight - height3;

txtROIstep = uicontrol(tabOptions,'Style','text',...
                'Tag','txtROIstep',...
                'BackgroundColor',color.bgc{2},...
                'String','ROI must step by: XX','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight widthbtn height3]);
currentheight = currentheight - height3;


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
currentheight = currentheight - 0.01;
txt1 = uicontrol(tabOptions,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Minimap Characteristics',...
                'Units','normalized',...
                'FontWeight','Bold',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight 0.9 0.02]);
currentheight = currentheight - height3;

txtMS = uicontrol(tabOptions,'Style','text',...
                'Tag','txtMS',...
                'BackgroundColor',color.bgc{2},...
                'String','Minimap size [um]: XX XX','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight widthbtn height3]);
currentheight = currentheight - height3;

txtNumImage = uicontrol(tabOptions,'Style','text',...
                'Tag','txtNumImage',...
                'BackgroundColor',color.bgc{2},...
                'String','Images to populate Minimap: XX XX','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight widthbtn height3]);
currentheight = currentheight - height3;

txtSampleSize = uicontrol(tabOptions,'Style','text',...
                'Tag','txtSampleSize',...
                'BackgroundColor',color.bgc{2},...
                'String','Minimap Sample Size: XX XX','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight widthbtn height3]);
currentheight = currentheight - height3;

txtStageToMinimapConversion = uicontrol(tabOptions,'Style','text',...
                'Tag','txtStageToMinimapConversion',...
                'BackgroundColor',color.bgc{2},...
                'String','Minimap conversion: XX XX','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight widthbtn 2.*height3]);
currentheight = currentheight - height3;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

width_ed = 0.5;
offset_ed = 0.6;
currentheight = currentheight - 0.01;
txt1 = uicontrol(tabOptions,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Image Contrast (Can Edit)',...
                'Units','normalized',...
                'FontWeight','Bold',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight 0.9 0.02]);
currentheight = currentheight - height3;

txtMainImageContrast = uicontrol(tabOptions,'Style','text',...
                'Tag','txtMainImageContrast',...
                'BackgroundColor',color.bgc{2},...
                'String','Main Image Contrast:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight width_ed height3]);
editMainImageContrast = uicontrol(tabOptions,'Tag','editMainImageContrast','Style','edit',...
                'String','#','Units','normalized',...
                'HorizontalAlignment','Center',...
                'BackgroundColor',color.bgc{1},...
                'Callback',@GUI_Callback_editMainImageContrast,...
                'Position',[offset_ed currentheight 0.2 height3]);
currentheight = currentheight - height3;

txtMinimapContrast = uicontrol(tabOptions,'Style','text',...
                'Tag','txtMinimapContrast',...
                'BackgroundColor',color.bgc{2},...
                'String','Minimap Contrast:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight width_ed height3]);
editMinimapContrast = uicontrol(tabOptions,'Tag','editMinimapContrast','Style','edit',...
                'String','#','Units','normalized',...
                'HorizontalAlignment','Center',...
                'BackgroundColor',color.bgc{1},...
                'Callback',@GUI_Callback_editMinimapContrast,...
                'Position',[offset_ed currentheight 0.2 height3]);
currentheight = currentheight - height3;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
currentheight = currentheight - 0.01;
txt2 = uicontrol(tabOptions,'Style','text',...
                'BackgroundColor',color.bgc{2},...
                'String','Stage Limits (Can Edit)',...
                'Units','normalized',...
                'FontWeight','Bold',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight 0.9 0.02]);
currentheight = currentheight - height3;

txtZOffset = uicontrol(tabOptions,'Style','text',...
                'Tag','txtZOffset',...
                'BackgroundColor',color.bgc{2},...
                'String','Z-Axis Offset [um]:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight width_ed height3]);
editZOffset = uicontrol(tabOptions,'Tag','editZOffset','Style','edit',...
                'String','#','Units','normalized',...
                'HorizontalAlignment','Center',...
                'BackgroundColor',color.bgc{1},...
                'Position',[offset_ed currentheight 0.2 height3]);
currentheight = currentheight - height3;

txtZMax = uicontrol(tabOptions,'Style','text',...
                'Tag','txtZMax',...
                'BackgroundColor',color.bgc{2},...
                'String','Z-Axis Max [um]:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight width_ed height3]);
editZMax = uicontrol(tabOptions,'Tag','editZMax','Style','edit',...
                'String','#','Units','normalized',...
                'HorizontalAlignment','Center',...
                'BackgroundColor',color.bgc{1},...
                'Position',[offset_ed currentheight 0.2 height3]);
currentheight = currentheight - height3;

txtXMax = uicontrol(tabOptions,'Style','text',...
                'Tag','txtXMax',...
                'BackgroundColor',color.bgc{2},...
                'String','X-Axis Max [um]:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight width_ed height3]);
editXMax = uicontrol(tabOptions,'Tag','editXMax','Style','edit',...
                'String','#','Units','normalized',...
                'HorizontalAlignment','Center',...
                'BackgroundColor',color.bgc{1},...
                'Position',[offset_ed currentheight 0.2 height3]);
currentheight = currentheight - height3;
txtYMax = uicontrol(tabOptions,'Style','text',...
                'Tag','txtYMax',...
                'BackgroundColor',color.bgc{2},...
                'String','Y-Axis Max [um]:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[leftX currentheight width_ed height3]);
editYMax = uicontrol(tabOptions,'Tag','editYMax','Style','edit',...
                'String','#','Units','normalized',...
                'HorizontalAlignment','Center',...
                'BackgroundColor',color.bgc{1},...
                'Position',[offset_ed currentheight 0.2 height3]);
currentheight = currentheight - height3;
 