function GUI_makeGUI_BtnPopupAndChkBox(hTabGroup,strName,strLongName,strPopup,strBtn,height1,handlesBtn,handlesPopup,handlesChkEnabled)
heightval = 0.03;
width1 = 0.6;
width2 = 0.25;
left1 = 0.05;
left2 = left1+width1+0.02;
height2 = height1+heightval;
fontSize1 = 9;

[color] =  GUI_Colors();

txtDataType = uicontrol(hTabGroup,'Style','text',...
                'Tag',['txtDatatype_' strName],...
                'String',strLongName,'Units','normalized',...
                'HorizontalAlignment','Left',...
                'BackgroundColor',color.bgc{2},...
                'FontSize',fontSize1,...
                'Position',[left1 height2 width1 heightval]);

btnValue = uicontrol(hTabGroup,'Style','pushbutton',...
                'Tag',['btnValue' strName],...
                'Callback',handlesBtn,...
                'String',strBtn,...
                'Units','normalized',...
                'FontSize',fontSize1,...
                'HorizontalAlignment','Left',...
                'Position',[left2 height1 width2 heightval]);
            
popupValue = uicontrol(hTabGroup,'Style','popupmenu',...
                'Tag',['popupValue' strName],...
                'Callback',handlesPopup,...
                'String',strPopup,'Units','normalized',...
                'BackgroundColor',color.bgc{1},...
                'Position',[left1 height1 width1 heightval]);
            
chkEnabled= uicontrol(hTabGroup,'Tag',['chkEnabled' strName],...
                'Style','checkbox','Value',1,...
                'Callback',handlesChkEnabled,...
                'BackgroundColor',color.bgc{2},...
                'String','Enable','Units','normalized',...
                'HorizontalAlignment','Right',...
                'FontSize',fontSize1,...
                'Position',[left2 height2 width2 heightval]);  
