function GUI_makeGUI_PopupAndChkBox(hTabGroup,strName,strLongName,strPopup,height1,handlesPopup,handlesChkEnabled)
heightval = 0.03;
width1 = 0.6;
width2 = 0.25;
width3 = 0.9;
left1 = 0.01;
left2 = left1+width1+0.02;
height2 = height1+heightval;
% fontSize1 = 9;

[color] =  GUI_Colors();

txtDataType = uicontrol(hTabGroup,'Style','text',...
                'Tag',['txtDatatype_' strName],...
                'String',strLongName,'Units','normalized',...
                'HorizontalAlignment','Left',...
                'BackgroundColor',color.bgc{2},...
                'Position',[left1 height2 width1 heightval]);
            
popupValue = uicontrol(hTabGroup,'Style','popupmenu',...
                'Tag',['popupValue' strName],...
                'Callback',handlesPopup,...
                'String',strPopup,'Units','normalized',...
                'BackgroundColor',color.bgc{1},...
                'Position',[left1 height1 width3 heightval]);
            
chkEnabled= uicontrol(hTabGroup,'Tag',['chkEnabled' strName],...
                'Style','checkbox','Value',1,...
                'Callback',handlesChkEnabled,...
                'BackgroundColor',color.bgc{2},...
                'String','Enable','Units','normalized',...
                'HorizontalAlignment','Right',...
                'Position',[left2 height2 width2 heightval]);  
