function GUI_makeGUI_LogPanel(hTabGroup)
% draws the log axes window on the right

[color] =  GUI_Colors(); %Background colors, 'BackgroundColor',bgc{1},...

panelLog = uipanel(hTabGroup,...
        'Position',[0.05 0.0 0.85 1],...
        'Title','Status',...
        'BackgroundColor',color.bgc{1});
txtLog = uicontrol('Parent',panelLog,...
    'Style','text','Tag','txtLog',...
    'String','','Units','normalized',...
    'BackgroundColor',color.bgc{1},...
    'HorizontalAlignment','Left',...
    'FontSize',10,...
    'Position',[0 0 1 1]);