function [handles] = GUI_makeGUI(input_options)
M_version = version('-release'); %Get version of matlab for v0 stuff

guiwidth = 900;
guiheight = 800;

mainFigure = figure('Toolbar','none','Menu','none','Units','pixels',...
    'Resize','off','position',[0 0 guiwidth guiheight],...
    'NumberTitle','off',...
    'Visible','on',...
    'tag','figureMain',...
    'CloseRequestFcn',@CLOSE_GUI,...
    'Name','Data Acquisition');

movegui(mainFigure,'east');
[color] =  GUI_Colors();

if strcmpi(M_version, '2009a')
    hLeftGroup = uitabgroup('v0','TabLocation','top',...
        'FlowDirection','bottomup',...
        'TabLocation','left',...
        'Position',[0 0.0 0.35 0.95],...
        'BackgroundColor',color.bgc{2});
else
    GUI_disableWarnings();
    hLeftGroup = uitabgroup('TabLocation','top',...
        'FlowDirection','bottomup',...
        'TabLocation','left',...
        'Position',[0 0.0 0.35 0.95],...
        'BackgroundColor',color.bgc{2});
end
hTopGroup = uipanel('Position',[0.35 0.0 0.65 0.1],...
    'BackgroundColor',color.bgc{2},...
    'BorderType','none');
hMiddleGroup = uipanel('Position',[0.35 0.1 0.65 0.85],...
    'BackgroundColor',color.bgc{2},...
    'BorderType','none');
hLogGroup = uipanel('Position',[0.35 0.95 0.65 0.05],...
    'BackgroundColor',color.bgc{2},...
    'BorderType','none');
hDataSetGroup = uipanel('Position',[0.0 0.95 0.35 0.05],...
    'BackgroundColor',color.bgc{2},...
    'BorderType','none');

GUI_makeGUI_LeftPanel(hLeftGroup,M_version);
GUI_makeGUI_MiddlePanel(hMiddleGroup);
% GUI_makeGUI_TopPanel(hTopGroup);
GUI_makeGUI_LogPanel(hLogGroup);
GUI_makeGUI_DataSetPanel(hDataSetGroup);

axesMain = axes('Position',[0.40 0.455 0.55 0.45],...
    'Tag','axesMain',...
    'ButtonDownFcn',@GUI_Callback_axesMain,...
    'HitTest','off',...
    'Parent',mainFigure);
axesMiniMap = axes('Position',[0.36 0.13 0.27 0.24],...
    'Tag','axesMinimap',...
    'ButtonDownFcn',@GUI_Callback_axesMinimap,...
    'HitTest','off',...
    'Parent',mainFigure);
axesPlot = axes('Position',[0.71 0.15 0.25 0.2],...
    'Tag','axesPlot',...
    'ButtonDownFcn',@GUI_Callback_axesPlot,...
    'HitTest','off',...
    'FontSize',7.5,...
    'Parent',mainFigure);

% keep track of the panels handles too
handles = guihandles(mainFigure);
handles.panels = struct();
handles.panels.figure = mainFigure;
handles.panels.left = hLeftGroup;
handles.panels.top = hTopGroup;
handles.panels.middle = hMiddleGroup;
handles.panels.bottom = hLogGroup;

% handles.ui = struct();
% handles.ui.screensize = smallwindow;

[handles] = GUI_init(handles,input_options); % init GUI

set(mainFigure,'Name',['SP-IRIS Acquisition ' handles.const.version]);
guidata(mainFigure,handles);