function handles = GUI_makePopup_FocusOffset(handles)
%% Constants
[color] =  GUI_Colors();

fHeight = 80;
fWidth = 530;
currentheight = 0.81;

%% Display focus image
icon = imread(handles.const.focusImage);
pos = get(handles.panels.figure,'Position');

posIcon = [pos(1)+2*pos(3)/3 pos(2)+pos(4)/2-size(icon,1)/2 size(icon,2) size(icon,1)];
Icon = figure('Position',posIcon,...
    'Resize','off','MenuBar','none','CloseRequestFcn',@CLOSE_popupFocusOffset);
imshow(icon);

%% Display message
posTxt = [posIcon(1)-posIcon(3)/3 posIcon(2)-fHeight fWidth fHeight];

popupFigure = figure('Toolbar','none','Menu','none','Units','pixel',...
    'Resize','off','position',posTxt,...
    'NumberTitle','off',...
    'tag','popupFigure',...
    'CloseRequestFcn',@CLOSE_popupFocusOffset,...
    'Name','Determine Focus Offset');

txtFocus1 = uicontrol(popupFigure,'Style','text',...
    'BackgroundColor',color.bgc{3},...
    'FontSize',9,...
    'String','Chip offset must be determined.','Units','normalized',...
    'HorizontalAlignment','Center',...
    'Position',[0.05 currentheight 0.9 0.18]);
currentheight = currentheight - 0.19;

txtFocus3 = uicontrol(popupFigure,'Style','text',...
    'BackgroundColor',color.bgc{3},...
    'FontSize',9,...
    'String','Use preview and main GUI to move the stages to the nearby corner (shown above).','Units','normalized',...
    'HorizontalAlignment','Center',...
    'Position',[0.05 currentheight 0.9 0.18]);
currentheight = currentheight - 0.19;

txtFocus4 = uicontrol(popupFigure,'Style','text',...
    'BackgroundColor',color.bgc{3},...
    'FontSize',9,...
    'String','Closing this popup or pressing continue will store the offset values and continue.','Units','normalized',...
    'HorizontalAlignment','Center',...
    'Position',[0.05 currentheight 0.9 0.18]);
currentheight = currentheight - 0.19;

btnContinue  = uicontrol(popupFigure,'Tag','btnContinue',...
    'Style','pushbutton',...
    'String','Continue','Units','normalized',...
    'Callback',@CLOSE_popupFocusOffset,...
    'HorizontalAlignment','Left',...
    'Position',[0.35 0.01 0.3 0.3]);

handles_popup = guihandles(popupFigure);
handles_popup.icon = Icon;
handles_popup.mainGUI = handles;
figure(Icon);
figure(popupFigure);
guidata(popupFigure, handles_popup); %save handles data
guidata(Icon, handles_popup); %save handles data
