function [handles,popupFigure] = GUI_makePopup_ArrayAdjust(handles)
%% Constants
[color] =  GUI_Colors();
fHeight = 225;
fWidth = 200;
pos = get(handles.panels.figure,'Position');


%% Display message
popupFigure = figure('Toolbar','none','Menu','none','Units','pixel',...
    'Resize','off','position',[pos(1)+pos(3)/2 pos(2)+pos(4)/2 fWidth fHeight],...
    'NumberTitle','off',...
    'tag','popupFigure',...
    'CloseRequestFcn',@CLOSE_popupLoadChip,...
    'Name','Array: Adjustment');
%     'WindowStyle','modal',...


txtLoadChip = uicontrol(popupFigure,'Style','text',...
    'BackgroundColor',color.bgc{3},...
    'FontSize',10,...
    'String','Center the spot in the image using the XY button in the Instrument Tab. Press done when centered.','Units','normalized',...
    'HorizontalAlignment','Center',...
    'Position',[0.01 0.45 0.98 0.5]);
%     'Position',[0.01 0.75 0.98 0.25]);

% btnMoveYUp = uicontrol(popupFigure,'Tag','btnMoveYUp','Style','pushbutton',...
%     'String','Y+','Units','normalized',...
%     'Callback',@GUI_Callback_btnArrayAdjust_MoveYUp,...
%     'Position',[0.35 0.55 0.3 0.25]);
% btnMoveYDown = uicontrol(popupFigure,'Tag','btnMoveYDown','Style','pushbutton',...
%     'String','Y-','Units','normalized',...
%     'Callback',@GUI_Callback_btnArrayAdjust_MoveYDown,...
%     'Position',[0.35 0.3 0.3 0.25]);
% btnMoveXRight = uicontrol(popupFigure,'Tag','btnMoveXRight','Style','pushbutton',...
%     'String','X-','Units','normalized',...
%     'Callback',@GUI_Callback_btnArrayAdjust_MoveXRight,...
%     'Position',[0.65 0.3 0.3 0.25]);
% btnMoveXLeft = uicontrol(popupFigure,'Tag','btnMoveXLeft','Style','pushbutton',...
%     'String','X+','Units','normalized',...
%     'Callback',@GUI_Callback_btnArrayAdjust_MoveXLeft,...
%     'Position',[0.05 0.3 0.3 0.25]);
            
btnContinue  = uicontrol(popupFigure,'Tag','btnContinue',...
    'Style','pushbutton',...
    'String','Done','Units','normalized',...
    'Callback',@CLOSE_popupArrayAdjust,...
    'HorizontalAlignment','Left',...
    'Position',[0.05 0.01 0.3 0.2]);

btnVideo  = uicontrol(popupFigure,'Tag','btnVideo',...
    'Style','pushbutton',...
    'String','Example Video','Units','normalized',...
    'Callback',@VIDEO_ArrayAdjust,...
    'HorizontalAlignment','Left',...
    'Position',[0.55 0.01 0.4 0.2]);

handles_popup = guihandles(popupFigure);
handles_popup.mainGUI = handles;
guidata(popupFigure, handles_popup); %save handles data
