function GUI_makeGUI_TopPanel(hTabGroup)
% draws the main axes window in the center

%% DATA AREA
btnStartx = 0.0115;
btnRows1 =0.25;
% btnRows2 =0.26;
btnFont1 = 7;
btnWidth = 0.15;
% btnHeight = 0.4;
btnHeight = 1-2*btnRows1;

[color] =  GUI_Colors();
offcolor = color.btnOff;

btnHistogram =  uicontrol(hTabGroup,'Style','pushbutton',...
                'Tag','btnHistogram',...
                'Callback',@GUI_Callback_btnHist_Image,...
                'String','Histogram','Units','normalized',...
                'HorizontalAlignment','Left',...
                'FontSize',btnFont1,'BackgroundColor',offcolor,...
                'Position',[btnStartx btnRows1 btnWidth btnHeight]);  
btnStartx = btnStartx + btnWidth;

btnPan =  uicontrol(hTabGroup,'Style','pushbutton',...
                'Tag','btnPan',...
                'Callback',@GUI_Callback_btnPan,...
                'String','Pan','Units','normalized',...
                'HorizontalAlignment','Left',...
                'FontSize',btnFont1,'BackgroundColor',offcolor,...
                'Position',[btnStartx btnRows1 btnWidth btnHeight]);  
btnStartx = btnStartx + btnWidth;

btnZoomIn =  uicontrol(hTabGroup,'Style','pushbutton',...
                'Tag','btnZoomIn',...
                'Callback',@GUI_Callback_btnZoomIn,...
                'String','Zoom In','Units','normalized',...
                'HorizontalAlignment','Left',...
                'FontSize',btnFont1,'BackgroundColor',offcolor,...
                'Position',[btnStartx btnRows1 btnWidth btnHeight]);
btnStartx = btnStartx + btnWidth;

btnZoomOut =  uicontrol(hTabGroup,'Style','pushbutton',...
                'Tag','btnZoomOut',...
                'Callback',@GUI_Callback_btnZoomOut,...
                'String','Zoom Out','Units','normalized',...
                'HorizontalAlignment','Left',...
                'FontSize',btnFont1,'BackgroundColor',offcolor,...
                'Position',[btnStartx btnRows1 btnWidth btnHeight]);
btnStartx = btnStartx + btnWidth;

btnZoomFull =  uicontrol(hTabGroup,'Style','pushbutton',...
                'Tag','btnZoomFull',...
                'Callback',@GUI_Callback_btnZoomFull,...
                'String','Zoom Full','Units','normalized',...
                'HorizontalAlignment','Left',...
                'FontSize',btnFont1,'BackgroundColor',offcolor,...
                'Position',[btnStartx btnRows1 btnWidth btnHeight]);
btnStartx = btnStartx + btnWidth;           

% %% DATASET SELECTION IN FIT
% leftX = 0.01;
% 
% heightx = 0.4;
% widthx = 0.94;
% currentheight = 0.6;
% 
% panelFitDatasets = uibuttongroup(hTabGroup,...
%                 'Tag','panelFitOptions',...
%                 'FontSize',7,...
%                 'BorderWidth',1,...
%                 'BorderType','line',...
%                 'BackgroundColor',color.bgc{2},...                
%                 'Title','Dataset Selection','Units','normalized',...
%                 'Position',[leftX currentheight widthx heightx]);
% leftpos = 0.02; 
% heightx = 0.9;
% yspace = 0.1;
% overspace = 0.1;
% Xspace = 0.19;
% fontsizeh = 6;
% radIntensity = uicontrol(panelFitDatasets,'Style','radiobutton',...
%                 'Tag','radIntensity',...
%                 'String','Intensity','Units','normalized',...
%                 'HorizontalAlignment','Left',...
%                 'FontSize',fontsizeh,...
%                 'BackgroundColor',color.bgc{2},...
%                 'Position',[leftpos yspace Xspace heightx]);
% leftpos = leftpos + overspace;            
% radContrast = uicontrol(panelFitDatasets,'Style','radiobutton',...
%                 'Tag','radContrast',...
%                 'String','Contrast','Units','normalized',...
%                 'HorizontalAlignment','Left',...
%                 'FontSize',fontsizeh,...
%                 'BackgroundColor',color.bgc{2},...
%                 'Position',[leftpos yspace Xspace heightx]);  
% leftpos = leftpos + overspace;
% radProcess = uicontrol(panelFitDatasets,'Style','radiobutton',...
%                 'Tag','radProcess',...
%                 'String','Process','Units','normalized',...
%                 'HorizontalAlignment','Left',...
%                 'FontSize',fontsizeh,...
%                 'BackgroundColor',color.bgc{2},...
%                 'Position',[leftpos yspace Xspace heightx]);
% 
% set(panelFitDatasets,'SelectionChangeFcn',@GUI_Callback_MainPlotStyle);
% 
%             
% leftpos = leftpos + overspace;            
% radDC = uicontrol(panelFitDatasets,'Style','radiobutton',...
%                 'Tag','radDC',...
%                 'String','DC','Units','normalized',...
%                 'HorizontalAlignment','Left',...
%                 'FontSize',fontsizeh,...
%                 'BackgroundColor',color.bgc{2},...
%                 'Position',[leftpos yspace Xspace heightx]);  
% leftpos = leftpos + overspace;            
% radRes = uicontrol(panelFitDatasets,'Style','radiobutton',...
%                 'Tag','radRes',...
%                 'String','Error','Units','normalized',...
%                 'HorizontalAlignment','Left',...
%                 'FontSize',fontsizeh,...
%                 'BackgroundColor',color.bgc{2},...
%                 'Position',[leftpos yspace Xspace heightx]);  
