function handles = GUI_makePopup_WelcomeAcquire(handles)
%% Constants
[color] =  GUI_Colors();
fHeight = 75;
fWidth = 350;

%% Display message
popupFigure = figure('Toolbar','none','Menu','none','Units','pixel',...
    'Resize','off','position',[pos(1) pos(2)+pos(4)/2-fHeight/2 fWidth fHeight],...
    'NumberTitle','off',...
    'tag','popupFigure',...
    'CloseRequestFcn',@CLOSE_popupWelcomeAcquire,...
    'Name','How to Load Chip');

txtAlignChip = uicontrol(popupFigure,'Style','text',...
    'BackgroundColor',color.bgc{3},...
    'FontSize',10,...
    'String','Use the main window to move the stages to the lower right spot in the array then press continue.','Units','normalized',...
    'HorizontalAlignment','Center',...
    'Position',[0.01 0.5 0.98 0.4]);

btnContinue  = uicontrol(popupFigure,'Tag','btnContinue',...
    'Style','pushbutton',...
    'String','Continue','Units','normalized',...
    'Callback',@CLOSE_popupWelcomeAcquire,...
    'HorizontalAlignment','Left',...
    'Position',[0.35 0.01 0.3 0.45]);

handles_popup = guihandles(popupFigure);
handles_popup.mainGUI = handles;
guidata(popupFigure, handles_popup); %save handles data
