function handles = GUI_makePopup_ChipInfo(handles)

%% Constants
[color] =  GUI_Colors();
pos = get(handles.panels.figure,'Position');

leftX = 0.2;
leftX2 = 0.01;
leftX3 = 0.1;
rightX = leftX2+0.3;

currentheight = 0.935;
height1 = 0.04;
height2 = 0.06;
height3 = 0.07;

width = 0.6;
width2 = 0.63;
width3 = 0.8;

fHeight = 380;
fWidth = 200;

thirdX1 = 0.01;
thirdX2 = 0.35;
thirdX3 = thirdX2+0.3;
thirdwidth = 0.34;
thirdwidth2 = 0.2;

%%
popupFigure = figure('Toolbar','none','Menu','none','Units','pixels',...
            'Resize','off','position',[pos(1)+pos(3)/2-fWidth/2 pos(2)+pos(4)/2-fHeight/2 fWidth fHeight],...
            'NumberTitle','off',...
            'tag','popupFigure',...
            'CloseRequestFcn',@CLOSE_popupChipInfo,...
            'Name','Chip Information');

txtDir = uicontrol(popupFigure,'Style','text',...
            'BackgroundColor',color.bgc{3},...
            'String','Save Folder Directory.',...
            'Units','normalized','FontSize',8,...
            'HorizontalAlignment','Left',...
            'Position',[leftX currentheight width height2]);
currentheight = currentheight - height1;

btnBrowseDir  = uicontrol(popupFigure,'Tag','btnBrowseDir',...
            'Style','pushbutton','FontSize',8,...
            'String','Browse','Units','normalized',...
            'Callback',@GUI_Callback_popupChipInfo_btnSaveFolder,...
            'HorizontalAlignment','Left',...
            'Position',[leftX2 currentheight 0.3 height2]);
txtValueSaveFolder = uicontrol(popupFigure,'Style','edit',...
            'Tag','txtValueSaveFolder','FontSize',8,...
            'BackgroundColor',color.bgc{1},...
            'String',getParams(handles,'Directory'),'Units','normalized',...
            'Callback',@GUI_Callback_popupChipInfo_editSaveFolder,...
            'HorizontalAlignment','Center',...
            'Position',[rightX currentheight width2 height2]);
currentheight = currentheight - height3;


txtID = uicontrol(popupFigure,'Style','text',...
            'BackgroundColor',color.bgc{3},'FontSize',8,...
            'String','Chip ID: ','Units','normalized',...
            'HorizontalAlignment','Center',...
            'Position',[0.05 currentheight-0.01 0.2 height2]);

editChipID = uicontrol(popupFigure,'Style','edit',...
            'Tag','editChipID','FontSize',8,...
            'BackgroundColor',color.bgc{1},...
            'String',getParams(handles,'ChipID'),'Units','normalized',...
            'HorizontalAlignment','Center',...
            'Position',[0.25 currentheight 0.6 height2]);
currentheight = currentheight - height3;

radPrescan = uicontrol(popupFigure,'Style','radiobutton',...
            'Tag','radPrescan','FontSize',8,...
            'String','Initial Scan','Units','normalized',...
            'HorizontalAlignment','Left',...
            'Callback',@GUI_Callback_radPrescan,...
            'Value',get(handles.radPrescan,'Value'),...
            'BackgroundColor',color.bgc{3},...
            'Position',[leftX3 currentheight width3 height2]);
currentheight = currentheight - height1;

radPostscan = uicontrol(popupFigure,'Style','radiobutton',...
            'Tag','radPostscan','FontSize',8,...
            'String','Post-Incubation Scan','Units','normalized',...
            'HorizontalAlignment','Left',...
            'Callback',@GUI_Callback_radPostscan,...
            'Value',get(handles.radPostscan,'Value'),...
            'BackgroundColor',color.bgc{3},...
            'Position',[leftX3 currentheight width3 height1]);
currentheight = currentheight - 3*height3;

panelArrayInfo = uipanel(popupFigure,...
                'Tag','panelArrayInfo',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BackgroundColor',color.bgc{2},...
                'BorderType','line',...
                'Title','Array Info','Units','normalized',...
                'Position',[0.03 currentheight 0.94 2.5*height3]);
panelheight = 0.75;
panelheight1 = 0.25;
panelheight2 = 0.35;

txtWidth = uicontrol(panelArrayInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},'FontSize',8,...
                'String','Width','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX2 panelheight thirdwidth2 panelheight1]);
            
txtHeight = uicontrol(panelArrayInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},'FontSize',8,...
                'String','Height','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX3 panelheight thirdwidth2 panelheight1]);
panelheight = panelheight - panelheight1;

txtArraySize = uicontrol(panelArrayInfo,'Style','text',...
                'Tag','txtArraySize','FontSize',8,...
                'BackgroundColor',color.bgc{2},...
                'String','Array Size:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight thirdwidth panelheight1]);
editArrayX = uicontrol(panelArrayInfo,'Style','edit',...
                'Tag','editArrayX','FontSize',8,...
                'BackgroundColor',color.bgc{1},...
                'String',getParams(handles,'ArrayX'),'Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX2 panelheight thirdwidth2 panelheight1]);
%                             'Callback',@GUI_Callback_editArrayX,...
editArrayY = uicontrol(panelArrayInfo,'Style','edit',...
                'Tag','editArrayY','FontSize',8,...
                'BackgroundColor',color.bgc{1},...
                'String',getParams(handles,'ArrayY'),'Units','normalized',...  
                'HorizontalAlignment','Center',...
                'Position',[thirdX3 panelheight thirdwidth2 panelheight1]);
%                             'Callback',@GUI_Callback_editArrayY,...              
panelheight = panelheight - panelheight2;

txtArrayPitch = uicontrol(panelArrayInfo,'Style','text',...
                'Tag','txtArrayDistance','FontSize',8,...
                'BackgroundColor',color.bgc{2},...
                'String','Spot pitch:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight thirdwidth panelheight1]);
editPitchX = uicontrol(panelArrayInfo,'Style','edit',...
                'Tag','editArrayPitchX','FontSize',8,...
                'BackgroundColor',color.bgc{1},...
                'String',getParams(handles,'PitchX'),'Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX2 panelheight thirdwidth2 panelheight1]);
editPitchY = uicontrol(panelArrayInfo,'Style','edit',...
                'Tag','editArrayPitchY','FontSize',8,...
                'BackgroundColor',color.bgc{1},...
                'String',getParams(handles,'PitchY'),'Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX3 panelheight thirdwidth2 panelheight1]);
currentheight = currentheight - 3*height3;

% popupSelectParticle = uicontrol(popupFigure,'Tag','popupSelectParticle','Style','popupmenu',...
%     'String',handles.const.ParticleType,'Units','normalized',...
%     'Value',get(handles.popupSelectParticle,'Value'),...
%     'BackgroundColor',color.bgc{2},...
%     'Position',[leftX currentheight width height2]);
% currentheight = currentheight - height1;

panelParticleInfo = uipanel(popupFigure,...
                'Tag','panelParticleInfo',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BackgroundColor',color.bgc{2},...
                'BorderType','line',...
                'Title','Particle Info','Units','normalized',...
                'Position',[0.03 currentheight 0.94 2.7*height3]);
panelheight = 0.75;
panelheight1 = 0.25;
panelheight2 = 0.4;

popupSelectParticle = uicontrol(panelParticleInfo,'Tag','popupSelectParticle','Style','popupmenu',...
                'String',handles.const.ParticleType,'Units','normalized',...
                'Value',get(handles.popupSelectParticle,'Value'),...
                'BackgroundColor',color.bgc{1},...
                'Position',[0.1 panelheight 0.8 panelheight1]);
%                             'Callback',@GUI_Callback_popupSelectParticle,'FontSize',8,...
panelheight = panelheight - panelheight2;

txtMinHist = uicontrol(panelParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},'FontSize',8,...
                'String','Min','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX2 panelheight thirdwidth2 panelheight1]);
            
txtMaxHist = uicontrol(panelParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},'FontSize',8,...
                'String','Max','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX3 panelheight thirdwidth2 panelheight1]);
panelheight = panelheight - panelheight1;

txtPSize = uicontrol(panelParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},'FontSize',8,...
                'String','Size:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight thirdwidth panelheight1]);
editMinHist = uicontrol(panelParticleInfo,'Style','edit',...
                'Tag','editMinHist','FontSize',8,...
                'BackgroundColor',color.bgc{1},...
                'String',getParams(handles,'MinHist'),'Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX2 panelheight thirdwidth2 panelheight1]);
%                             'Callback',@GUI_Callback_editMinHist,...
editMaxHist = uicontrol(panelParticleInfo,'Style','edit',...
                'Tag','editMaxHist','FontSize',8,...
                'BackgroundColor',color.bgc{1},...
                'String',getParams(handles,'MaxHist'),'Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX3 panelheight thirdwidth2 panelheight1]);
%                             'Callback',@GUI_Callback_editMaxHist,...
currentheight = currentheight - 3*height3;

panelRefParticleInfo = uipanel(popupFigure,...
                'Tag','panelRefParticleInfo',...
                'FontSize',7,...
                'BorderWidth',1,...
                'BackgroundColor',color.bgc{2},...
                'BorderType','line',...
                'Title','Reference Particle Info','Units','normalized',...
                'Position',[0.03 currentheight 0.94 2.7*height3]);
panelheight = 0.75;
panelheight1 = 0.25;
panelheight2 = 0.4;

popupSelectRefParticle = uicontrol(panelRefParticleInfo,'Tag','popupSelectRefParticle',...
                'Style','popupmenu',...
                'String',handles.const.ParticleType,'Units','normalized',...
                'Value',get(handles.popupSelectRefParticle,'Value'),...
                'BackgroundColor',color.bgc{1},...
                'Position',[0.1 panelheight 0.8 panelheight1]);
%                             'Callback',@GUI_Callback_popupSelectParticle,'FontSize',8,...
panelheight = panelheight - panelheight2;

txtMinHist = uicontrol(panelRefParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},'FontSize',8,...
                'String','Min','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX2 panelheight thirdwidth2 panelheight1]);
            
txtMaxHist = uicontrol(panelRefParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},'FontSize',8,...
                'String','Max','Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX3 panelheight thirdwidth2 panelheight1]);
panelheight = panelheight - panelheight1;

txtPSize = uicontrol(panelRefParticleInfo,'Style','text',...
                'BackgroundColor',color.bgc{2},'FontSize',8,...
                'String','Size:','Units','normalized',...
                'HorizontalAlignment','Left',...
                'Position',[thirdX1 panelheight thirdwidth panelheight1]);
editRefMinHist = uicontrol(panelRefParticleInfo,'Style','edit',...
                'Tag','editRefMinHist','FontSize',8,...
                'BackgroundColor',color.bgc{1},...
                'String',getParams(handles,'RefMinHist'),'Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX2 panelheight thirdwidth2 panelheight1]);
%                             'Callback',@GUI_Callback_editMinHist,...
editRefMaxHist = uicontrol(panelRefParticleInfo,'Style','edit',...
                'Tag','editRefMaxHist','FontSize',8,...
                'BackgroundColor',color.bgc{1},...
                'String',getParams(handles,'RefMaxHist'),'Units','normalized',...
                'HorizontalAlignment','Center',...
                'Position',[thirdX3 panelheight thirdwidth2 panelheight1]);
%                             'Callback',@GUI_Callback_editMaxHist,...
currentheight = currentheight - 1.1*height2;

btnOk  = uicontrol(popupFigure,'Tag','btnOk',...
    'Style','pushbutton','FontSize',8,...
    'String','Ok','Units','normalized',...
    'Callback',@GUI_Callback_btnChipInfo_popupOk,...
    'HorizontalAlignment','Left',...
    'Position',[leftX3 currentheight 0.3 height2]);
btnCancel  = uicontrol(popupFigure,'Tag','btnCancel',...
    'Style','pushbutton','FontSize',8,...
    'String','Cancel','Units','normalized',...
    'Callback',@GUI_Callback_btnChipInfo_popupCancel,...
    'HorizontalAlignment','Left',...
    'Position',[0.45 currentheight 0.4 height2]);

handles_popup = guihandles(popupFigure);
handles_popup.keep = 0;
handles_popup.mainGUI = handles;
handles_popup.const.directories.data = handles.const.directories.data;
handles_popup.data.saveFolder = handles.data.saveFolder;
handles_popup.const.log = handles.const.log;
handles_popup.txtLog = handles.txtLog;
handles_popup.const.ParticleType = handles.const.ParticleType;

guidata(popupFigure, handles_popup); %save handles data